### ISSUE TITLE
Cannot create Users

### ISSUE THREAD

**Issue by LordRazor** [Mailu/Mailu#1062]
If I try to create a User on any Domain, it says 500 Internal Server Error.
A quick Look at the Logs of the admin Container provides this Error:

```
admin_1      | [2019-07-02 09:18:46,819] ERROR in app: Exception on /ui/user/create/CENSORED [POST]
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 28, in wrapper
admin_1      |     return callback(function, args, kwargs, dargs, dkwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 19, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/views/users.py", line 30, in user_create
admin_1      |     if form.validate_on_submit():
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
admin_1      |     return self.is_submitted() and self.validate()
admin_1      |   File "/usr/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
admin_1      |     return super(Form, self).validate(extra)
admin_1      |   File "/usr/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
admin_1      |     if not field.validate(self, extra):
admin_1      |   File "/usr/lib/python3.6/site-packages/wtforms/fields/core.py", line 206, in validate
admin_1      |     stop_validation = self._run_validation_chain(form, chain)
admin_1      |   File "/usr/lib/python3.6/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
admin_1      |     validator(form, self)
admin_1      |   File "/usr/lib/python3.6/site-packages/wtforms/validators.py", line 135, in __call__
admin_1      |     (self.max is not None and data > self.max):
admin_1      | TypeError: '>' not supported between instances of 'int' and 'str
```
I can create Domains however, but I cant edit them due to a similar Errror.

**Comment by kaiyou** [comment]
Could you please specify which version you are running? This sounds like a nasty bug introduced in recent changes to the ui.

**Comment by LordRazor** [comment]
I'm currently running Mailu Version 1.6, Docker states that all Images are up to date.

**Comment by LordRazor** [comment]
Bug still present in newest Version. Bump.

**Comment by kaiyou** [comment]
Since I cannot reproduce I now think this is related to your browser or your database.

If it is the browser, my guess is it sends an incorrect value in the quota field, possibly due to html5 sliders not being well handled. Could you test with another browser?

If it is the database, my best guess is your domain table having the wrong schema for some reason. What type of database do you use? Do you have production data in there?

**Comment by LordRazor** [comment]
Indeed, it was the Database. I recently switched the Database-Backend from sqlite3 to mysql. Somehow the Converter switched the type of the `quota_bytes` field from bigint to text, which caused the Error since Python tried to compare a string to an integer. Changing the field type manually in both the `user` and the `domain` table solved the problem. Thank you very much for the nudge in the right direction.
