### ISSUE TITLE
Services that require redis do not advertise or fail gracefully

### ISSUE THREAD

**Issue by SirPole** [Mailu/Mailu#1153]
**Disclaimer:** I'm not using Mailu recommended docker-compose, Mailu simply connects to available redis container I have running through another network. 

Hello,

I've just updated from 1.6 to 1.7 and one of the changes I noticed is that rspamd now requires redis. 

Problem is, that the services (be it antispam or imap for example) don't let user know that redis is not available to them until it times out with not human friendly error message. From user's perspecitve, it seems like it's taking an awful lot of time to start... 

It is also not mentioned in the documentation which services need redis.

```
mail-antispam | Traceback (most recent call last):
mail-antispam |   File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 361, in call
mail-antispam |     result = fn(*args, **kwargs)
mail-antispam |   File "/usr/lib/python3.7/site-packages/socrate/system.py", line 12, in resolve_hostname
mail-antispam |     return socket.gethostbyname(hostname)
mail-antispam | socket.gaierror: [Errno -2] Name does not resolve
mail-antispam |
mail-antispam | The above exception was the direct cause of the following exception:
mail-antispam |
mail-antispam | Traceback (most recent call last):
mail-antispam |   File "/start.py", line 14, in <module>
mail-antispam |     os.environ["REDIS_ADDRESS"] = system.resolve_address(os.environ.get("HOST_REDIS", "redis"))
mail-antispam |   File "/usr/lib/python3.7/site-packages/socrate/system.py", line 20, in resolve_address
mail-antispam |     ip_address = resolve_hostname(hostname)
mail-antispam |   File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 292, in wrapped_f
mail-antispam |     return self.call(f, *args, **kw)
mail-antispam |   File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 358, in call
mail-antispam |     do = self.iter(retry_state=retry_state)
mail-antispam |   File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 332, in iter
mail-antispam |     six.raise_from(retry_exc, fut.exception())
mail-antispam |   File "<string>", line 3, in raise_from
mail-antispam | tenacity.RetryError: RetryError[<Future at 0x7fb51eb426d8 state=finished raised gaierror>]
```

Not sure if this is something to fix... At least it may help somebody with the same issue 🙂

**Comment by muhlemmer** [comment]
Yes, we are aware of the lack of logging. See #1120. Thanks for the report.

**Comment by SirPole** [comment]
Thanks for the heads up! :)
