### ISSUE TITLE
Colon in account password causes HTTP basic auth to fail.

### ISSUE THREAD

**Issue by cha0s** [Mailu/Mailu#1174]
Logs gotten from `mailu_admin_`:

```
[2019-09-19 18:53:16,009] ERROR in app: Exception on /internal/auth/basic [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/mailu/internal/views/auth.py", line 43, in basic_authentication
    user_email, password = base64.b64decode(encoded).split(b":")
ValueError: too many values to unpack (expected 2)
```

I found this trying to get into webdav. `mailu_front_1` logs had: `auth request unexpected status: 500 while sending to client`. This is when trying to access radicale (hopefully all these keywords will help people searching the web as I was fruitlessly).

**Comment by kaiyou** [comment]
This should be fixed by #1316
