### ISSUE TITLE
fetchmail crashes due to exception

### ISSUE THREAD

**Issue by Al2Klimov** [Mailu/Mailu#1295]
```
Traceback (most recent call last):
  File "/fetchmail.py", line 93, in <module>
    run(os.environ.get("DEBUG", None) == "True")
  File "/fetchmail.py", line 47, in run
    fetches = requests.get("http://admin/internal/fetch").json()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Al2Klimov** [comment]
I'll fix it by myself.

**Comment by Al2Klimov** [comment]
Feel free to assign this to me.

**Comment by kaiyou** [comment]
We do not assign specifically, but if you found the cause and fixed it, please open a PR

**Comment by Al2Klimov** [comment]
Already done and referenced before my previous post: #1296

**Comment by kaiyou** [comment]
Sorry indeed, my mobile client does not show these references and I was backlogging 2w of comments 😃
