### ISSUE TITLE
pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>

### ISSUE THREAD

**Issue by tinonaumann** [Mailu/Mailu#1416]
I get following issues every 30s by default 1.7 installation on a fresh installed server with Docker swarm and Traefik v2

> mailu_antispam.1.ms1plfqjvixh@mx01.domain.de    | 2020-03-21 09:42:08 #6(rspamd_proxy) <a17380>; proxy; proxy_accept_socket: accepted milter connection from 10.0.3.4 port 58588
> mailu_antispam.1.ms1plfqjvixh@mx01.domain.de    | 2020-03-21 09:42:08 #6(rspamd_proxy) <a17380>; milter; rspamd_milter_process_command: got connection from 127.0.0.1:46847
> mailu_antispam.1.ms1plfqjvixh@mx01.domain.de    | 2020-03-21 09:42:08 #6(rspamd_proxy) <a17380>; proxy; proxy_milter_finish_handler: finished milter connection

> mailu_smtp.1.0104l4p8850z@mx01.domain.de    | Mar 21 09:42:08 mx01 postfix/smtpd[190]: connect from localhost[127.0.0.1]
> mailu_smtp.1.0104l4p8850z@mx01.domain.de    | Mar 21 09:42:08 mx01 postfix/smtpd[190]: disconnect from localhost[127.0.0.1] quit=1 commands=1

> mailu_imap.1.kyvzwzfbnvmz@mx01.domain.de    | Mar 21 09:42:15 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<qFCgN1qhb5Z/AAAB>

Mail sending and receiving is working properly, also the admin ui but why causes rspamd an empty pop3-login?

docker-compose.yml
```
# Swarm workaround
# - switch ports-mode from "overlay" "host"
# - add "endpoint_mode: dnsrr" in deploy section of fromt service
# - hardcode mailu/traefik-certdumper version to master to support traefik v2
# - add TRAEFIK_VERSION=v2 variable to certdumper environment
# - dissable healthcheck for front, admin, webmail (if rainloop)
# - dissable antivirus vor dev entironment
# - dissable webdav vor dev entironment
# - dissable webmail vor dev entironment
# - set fetchmail replica to 0 because of error                                 
        #Traceback (most recent call last):
        #  File "/fetchmail.py", line 94, in <module>
        #    run(os.environ.get("DEBUG", None) == "True")
        #  File "/fetchmail.py", line 48, in run
        #    fetches = requests.get("http://admin/internal/fetch").json()
        #  File "/usr/lib/python3.7/site-packages/requests/models.py", line 898, in json
        #    return complexjson.loads(self.text, **kwargs)
        #  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
        #    return _default_decoder.decode(s)
        #  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
        #    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        #  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
        #    raise JSONDecodeError("Expecting value", s, err.value) from None
        #json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


version: '3.6'

services:
# External dependencies
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

# Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master}
    env_file: .env
    logging:
      driver: json-file
    ports:
      - target: 25
        published: 25
        mode: host
      - target: 465
        published: 465
        mode: host
      - target: 587
        published: 587
        mode: host
      - target: 110
        published: 110
        mode: host
      - target: 995
        published: 995
        mode: host
      - target: 143
        published: 143
        mode: host
      - target: 993
        published: 993
        mode: host
    volumes:
      - certificates:/certs
      - overrides_nginx:/overrides
    networks:
      - traefik-public
      - default
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      labels:
        - traefik.enable=true
        - traefik.http.routers.mailu-http.rule=Host(`mail.$DOMAIN`)
        - traefik.http.routers.mailu-http.entrypoints=http
        - traefik.http.routers.mailu-http.middlewares=redirect-to-https@docker
        - traefik.http.routers.mailu-https.tls=true
        - traefik.http.routers.mailu-https.tls.certresolver=http
        - traefik.http.routers.mailu-https.entrypoints=https
        - traefik.http.routers.mailu-https.rule=Host(`mail.$DOMAIN`)
        - traefik.http.services.mailu.loadbalancer.server.port=80
        - traefik.http.routers.mailu-https.tls.domains[0].main=$DOMAIN
        - traefik.http.routers.mailu-https.tls.domains[0].sans=$HOSTNAMES,mail.$DOMAIN,webmail.$DOMAIN,imap.$DOMAIN,smtp.$DOMAIN,dav.$DOMAIN
    healthcheck:
      disable: true

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master}
    env_file: .env
    volumes:
      - data:/data
      - dkim:/dkim
    deploy:
      replicas: 1
    healthcheck:
      disable: true

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-master}
    env_file: .env
    volumes:
      - mail:/mail
      - overrides_imap:/overrides
      - data:/data
    deploy:
      replicas: 1

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-master}
    env_file: .env
    volumes:
      - mailqueue:/queue
      - overrides_smtp:/overrides
      - data:/data
    deploy:
      replicas: 1

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-master}
    env_file: .env
    volumes:
      - filter:/var/lib/rspamd
      - dkim:/dkim
      - overrides_rspamd:/etc/rspamd/override.d
    deploy:
      replicas: 1

  # Optional services

  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}${ANTIVIRUS:-clamav}:${MAILU_VERSION:-master}
    env_file: .env
    volumes:
      - filter:/data
    deploy:
      replicas: 1

  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}${WEBDAV:-radicale}:${MAILU_VERSION:-master}
    env_file: .env
    volumes:
      - dav:/data
    deploy:
      replicas: 1

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-master}
    env_file: .env
    volumes:
      - data:/data
    deploy:
      replicas: 0

  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}${WEBMAIL:-roundcube}:${MAILU_VERSION:-master}
    env_file: .env
    volumes:
      - webmail:/data
    deploy:
      replicas: 1
    healthcheck:
      disable: true

  certdumper:
    restart: always
    image: mailu/traefik-certdumper:master
    environment:
      - DOMAIN=$DOMAIN
      - TRAEFIK_VERSION=v2
    volumes:
      - traefik_certificates:/traefik
      - certificates:/output

volumes:
  traefik_certificates:
    external: true
  certificates:
  data:
  dav:
  dkim:
  filter:
  mail:
  mailqueue:
  overrides_imap:
  overrides_nginx:
  overrides_rspamd:
  overrides_smtp:
  redis:
  webmail:

networks:
  traefik-public:
    external: true
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET:-10.0.87.0/24}`

```
.env
```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for stack flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Version of Mailu (value: 1.7, master)
MAILU_VERSION=1.7

# Set to a randomly generated 16 bytes string
SECRET_KEY=8NlYfJj9QzZuMzYw

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=10.0.3.0/24

# Main mail domain
DOMAIN=mx01.domain.de

# Hostnames for this server, separated with comas
HOSTNAMES=mx01.domain.de

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;1000/hour 

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=none

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=none

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mailu.io



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: PBKDF2, BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT)
PASSWORD_SCHEME=PBKDF2

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=DEBUG

###################################
# Database settings
###################################
DB_FLAVOR=sqlite

```

**Comment by ofthesun9** [comment]
That is the healthcheck doing its magic.
Nothing to worry about :-)

**Comment by tinonaumann** [comment]
confirmed, thank u

it never came to my mind to check this simple thing
