### ISSUE TITLE
Incoming Mails are not being stored - temporary failure

### ISSUE THREAD

**Issue by LordRazor** [Mailu/Mailu#1426]
In my Installation, incoming Mails are not being stored in the Mailbox. According to Logs, the SMTP-Container works just fine and redirects the incoming Mails to the IMAP-Container. However, the IMAP-Container won't process them due to the following Error:
```
imap_1       | Mar 31 12:40:09 lmtp([MY DOMAIN])<92><yI2rHAs6g15cAAAAJc3wBg>: Warning: Dict server timeout: No input for 30.025 secs (1 commands pending, oldest sent 30.025 secs ago: Lpriv/sieve/data/default, 30.026 in dict wait, 0.000 in other ioloops, 0.000 in locks) - reconnected
imap_1       | INFO:root:Connect
imap_1       | ERROR:asyncio:_GatheringFuture exception was never retrieved
imap_1       | future: <_GatheringFuture finished exception=Exception(500,)>
imap_1       | Traceback (most recent call last):
imap_1       |   File "/usr/lib/python3.6/site-packages/podop/dovecot.py", line 86, in process_lookup
imap_1       |     key, ns=(self.user if key_type == "priv" else None)
imap_1       |   File "/usr/lib/python3.6/site-packages/podop/table.py", line 35, in get
imap_1       |     raise Exception(request.status)
imap_1       | Exception: 500
```
and shortly after that, this one occurs:
```
imap_1       | Mar 31 12:40:39 lmtp([MY DOMAIN])<92><yI2rHAs6g15cAAAAJc3wBg>: Error: sieve: dict script: Failed to lookup data with id `default' for script `default' from path priv/sieve/data/default: Dict server timeout: No input since connected 30.030 secs ago (1 commands pending, oldest sent 60.055 secs ago: Lpriv/sieve/data/default, 60.056 in dict wait, 0.000 in other ioloops, 0.000 in locks) (reply took 60.055 secs (60.056 in dict wait, 0.000 in other ioloops, 0.000 in locks, reconnected 30.030 secs ago))
imap_1       | Mar 31 12:40:39 lmtp([MY DOMAIN])<92><yI2rHAs6g15cAAAAJc3wBg>: Error: sieve: default: parse failed
imap_1       | Mar 31 12:40:39 lmtp([MY DOMAIN])<92><yI2rHAs6g15cAAAAJc3wBg>: Error: sieve: Failed to open script `dict:proxy:/tmp/podop.socket:sieve;user=[MY DOMAIN]' for compile (temporary failure)
imap_1       | Mar 31 12:40:39 lmtp([MY DOMAIN])<92><yI2rHAs6g15cAAAAJc3wBg>: Error: sieve: Execution of script dict:proxy:/tmp/podop.socket:sieve;user=[MY DOMAIN] was aborted due to temporary failure
```
However, everything else like the redirects and administrative features works just fine.
I'm currently running Mailu 1.6 and I appreciate any help I might get. Thanks in advance.

**Comment by LordRazor** [comment]
Btw, I just noticed that in the Error, it uses two different types of quotation marks around the parameters. Could this be relevant?

**Comment by LordRazor** [comment]
Ok, I got it. For future reference if anyone has the same problem: In the User-Table of the Database, the `reply_startdate` and `reply_enddate` columns were declared the wrong type. they should have been `date`, but were `text`. This lead to a cascade of errors which ultimately resulted in the above. Fixing the column Type removes those Errors.

**Comment by zxpower** [comment]
Unfortunately - I face the same error, but the `user` table and your mentioned columns seems to be OK. Any other ideas?
