### ISSUE TITLE
Flask python exception (resolve_hostname) during docker-compose -p mailu exec admin flask mailu admin me domain.tld pass 

### ISSUE THREAD

**Issue by huvelyb** [Mailu/Mailu#1589]
When I setting up docker mailu environment, admin ui not reachable.
The command: docker-compose -p mailu exec admin flask mailu admin me domain.tld password raise an exception, problem maybe related that not able to resolve one or more hostname.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/socrate/system.py", line 11, in resolve_hostname
    return socket.gethostbyname(hostname)
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 515, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 254, in locate_app
    return find_best_app(script_info, module)
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 76, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 116, in call_factory
    return app_factory()
  File "/app/mailu/__init__.py", line 55, in create_app
    return create_app_from_config(config)
  File "/app/mailu/__init__.py", line 18, in create_app_from_config
    config.init_app(app)
  File "/app/mailu/configuration.py", line 109, in init_app
    self.resolve_host()
  File "/app/mailu/configuration.py", line 93, in resolve_host
    self.config[address] = system.resolve_address(self.config[host])
  File "/usr/lib/python3.7/site-packages/socrate/system.py", line 19, in resolve_address
    ip_address = resolve_hostname(hostname)
  File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/lib/python3.7/site-packages/tenacity/__init__.py", line 332, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7f4084d4c8d0 state=finished raised gaierror>]
```

Any clue? Maybe misconfiguration? 
On the host side, I shutdown postfix dovecot clamav related ports, so I think there is no port overlapping occured.

Cheers, Balazs

**Comment by Diman0** [comment]
If the web administration interface is not reachable. I'd start with troubleshooting this first. 
You could start with checking with the logs of the admin container (docker logs mailu_admin_1). Can you see any errors in here?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by huvelyb** [comment]
I had no time, so I installed tvial project within an hour, and my
whole mailing is working perfect now.There were some exception with
mailu, but I not interested it, because the reaction was not so fast
and the goal of the project (deployable within hours) is not working,
documentation depth is surface, so I have to decide to ignore this
solution for my mail system. 
Thank you. Thread can be closed...
Balázs

-----Original Message-----From: Dimitri Huisman <
notifications@github.com>Reply-To: Mailu/Mailu <
reply@reply.github.com>To:
Mailu/Mailu <Mailu@noreply.github.com>Cc: Jeefoo <
balazs.huvely@gmail.com>, Author <author@noreply.github.com>Subject:
Re: [Mailu/Mailu] Flask python exception (resolve_hostname) during
docker-compose -p mailu exec admin flask mailu admin me domain.tld
pass  (#1589)Date: Tue, 18 Aug 2020 10:26:11 -0700

If the web administration interface is not reachable. I'd start with
troubleshooting this first.

You could start with checking with the logs of the admin container
(docker logs mailu_admin_1). Can you see any errors in here?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
Hüvely Balázs István e.v.
+36-30-932-6818
Szerszámgépek, szőnyeg-, PVC-, laminált padló kereskedelem, 
munkavédelmi felszerelések kereskedelme,
fotográfiai szolgáltatások - balaphoto.hu
IT és biztonságtechnikai kamerarendszerek tervezése és kereskedelme

**Comment by sizeur** [comment]
I have the exact same error message on the last version of mailu (1.7). For what it worth the problem is only present with sqlite, if you select postgres for example it works fine.

**Comment by barrymichels** [comment]
I have the exact same issue with 1.9 and it only happens when I try to enable roundcube webmail. I'm using mysql.
Tried setting up the whole thing without webmail and then adding it later, but still couldn't get past this error.
Thanks @huvelyb for the suggestion. Giving docker-mailserver a try...
