### ISSUE TITLE
config-update command not working because of deprecated API: YAMLLoadWarning

### ISSUE THREAD

**Issue by vbence** [Mailu/Mailu#1647]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.7

## Description
```
/app/mailu/manage.py:180: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  new_config = yaml.load(sys.stdin)
Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/mailu/manage.py", line 242, in config_update
    user.set_password(password_hash, hash_scheme=hash_scheme, raw=True)
  File "/app/mailu/models.py", line 394, in set_password
    self.password = '{'+hash_scheme+'}' + password
TypeError: can only concatenate str (not "NoneType") to str
```

## Replication Steps
Create user.yaml containing:
```
users:
  - localpart: myuser
    domain: mydomain.org
    quota_bytes: 10000000000
```
and issue the command:
```
cat user.yml | docker-compose exec -T admin flask mailu config-update
```

## Expected behaviour
The modifications to the user are made.

**Comment by lub** [comment]
```
  File "/app/mailu/manage.py", line 242, in config_update
    user.set_password(password_hash, hash_scheme=hash_scheme, raw=True)
  File "/app/mailu/models.py", line 394, in set_password
    self.password = '{'+hash_scheme+'}' + password
TypeError: can only concatenate str (not "NoneType") to str
```

Can you try also specifying `password_hash` and `hash_scheme` like in the [example](https://mailu.io/1.7/cli.html?highlight=yaml#config-update)? I suspect the deprecation is just a warning and the real problem is the assumption, that there is always a password without checking it first.

On the other hand *if* this is actually the problem, does it make sense to allow creating users without password or should we just throw a better error message?

**Comment by vbence** [comment]
Hi, Thanks for the quick reply.

I was under the impression that the specified yaml gets _merged_ with the existing database, so keeping _localpart_ and _domain_ would serve as a compound key and any omitted values are left unchanged. My use case would be to mass-update users' settings. From your description this function is not created for that purpose.

Yes, I think an explicit check for required fields would improve the experience.

**Comment by ghostwheel42** [comment]
Hi.
The yaml.load() call is already replaced with yaml.safe_load() in master (and will be in 1.8).
It will be possible to _merge_ a configuration to update only some user or domain properties when #1604 is merged.
Alex

**Comment by lub** [comment]
I've updated the title to better reflect that the actual error/"Expected behaviour" is about merging existing users.

**Comment by ghostwheel42** [comment]
> And the #1604 won't fix the problem

The new **config-import** action from #1604 allows you to do this:

```
devel $ cat user.yaml 
user:
  - email: myuser@mydomain.org
    quota_bytes: 10000000000

devel $ flask mailu config-import -vu < user.yaml 
Modified user: 'myuser@mydomain.org' quota_bytes: 1000000000 -> 10000000000
Committing changes. Modified: user(1)
```
