### ISSUE TITLE
Postgresql does not seem to work properly "database" to address, and fails on raspberrypi arm64

### ISSUE THREAD

**Issue by guysoft** [Mailu/Mailu#1670]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [X ] Check if no issue or pull-request for this already exists.
- [ X ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ ❤️  ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
$> docker ps -a | grep mailu
7a8403df1a90        mailu/radicale:1.8                                 "/bin/sh -c 'radcal…"   41 minutes ago      Up 41 minutes (unhealthy)       5232/tcp       mailu_webda_1
$> grep MAILU_VERSION docker-compose.yml mailu.env

1.8 , also tried 1.7
```

## Description
I am following the setup instructions at: https://setup.mailu.io/1.7/

The setup works using sqlite, but when I try prosgress with the container selected I get:

## Replication Steps
1. create a setup either 1.7 or 1.8, and select "compose, then:
Which database back end would you like to use?> postgresql
Use the Postgresql from Mailu

## Expected behaviour
The following command  should work`, as explained in the post generation instructions of the Mailu configuration:
```
docker-compose -p mailu exec admin flask mailu admin admin gnethomelinux.com PASSWORD
```

## Logs
```
~$ sudo docker-compose -p mailu exec admin flask mailu admin admin gnethomelinux.com PASSWORD
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2262, in _wra_pool_connect
    return fn()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 363, in connect    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 760, in _checkot
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkou    rec = pool._do_get()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get    self._dec_overflow()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in _exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 129, in reraie
    raise value
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get    return self._create_connection()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _creat_onnection
    return _ConnectionRecord(self)
    return _ConnectionRecord(self)
    self.__connect(first_connect_check=True)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 639, in __connc    connection = pool._invoke_creator(self)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, i
onnect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 453, in cnect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "database" to address: Name de not resolve


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib/python3.8/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
````

I treid adding to the front container:

```
links:
  - "database:database"
```
but then got:

```
    raise value
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get    return self._create_connection()
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _createconnection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init_    self.__connect(first_connect_check=True)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 639, in __connet
    connection = pool._invoke_creator(self)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, inconnect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 453, in conect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to serve: Connection refused
        Is the server running on host "database" (172.19.0.22) and accepting
        TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/e3q8)
````

On the postgresql container I get:
```
database_1   |   File "/start.py", line 12, in setup
database_1   |     conn =  psycopg2.connect(user='postgres')
database_1   |   File "/usr/lib/python3.8/site-packages/psycopg2/__init__.py", line 127 in connect
database_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasyn)
database_1   | psycopg2.OperationalError: could not connect to server: No such file or
irectory
database_1   |  Is the server running locally and accepting
database_1   |  connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
database_1   |
database_1   | Unknown host QEMU_IFLA type: 50
database_1   | Unknown host QEMU_IFLA type: 51
database_1   | Unknown host QEMU_IFLA type: 50
database_1   | Unknown host QEMU_IFLA type: 51
database_1   | waiting for server to start....2020-10-25 15:20:06.416 UTC [25] LOG:  strting PostgreSQL 12.4 on x86_64-alpine-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0 64-bit
atabase_1   | 2020-10-25 15:20:06.428 UTC [25] LOG:  listening on Unix socket "/run/posgresql/.s.PGSQL.5432"
atabase_1   | 2020-10-25 15:20:06.441 UTC [25] LOG:  listening on Unix socket "/tmp/.s.GSQL.5432"
atabase_1   | 2020-10-25 15:20:06.647 UTC [29] FATAL:  could not request parent death sgnal: Invalid argument
atabase_1   | 2020-10-25 15:20:06.662 UTC [25] LOG:  startup process (PID 29) exited wih exit code 1
atabase_1   | 2020-10-25 15:20:06.663 UTC [25] LOG:  aborting startup due to startup pr
```

WiIl also note - there is an arm64 built for postgresql. Is it possible to just use that? Why is there a special container for mailu?

**Comment by lub** [comment]
> WiIl also note - there is an arm64 built for postgresql. Is it possible to just use that? Why is there a special container for mailu?

The custom postgresql image (and the supplied configuration for such a container in general) is deprecated as of 1.8, so if you are able to use the official image feel free to do that. It's basically the recommended way now, when you want to use postgres.

I gather you use arm64 then? Are you able to also test your config on x86? Maybe it's a bug with the arm64 version.

**Comment by guysoft** [comment]
What are the environment variables to set up the hostname, user and password that Maliu is using? Because they seem to be different with the official image.

**Comment by lub** [comment]
For that case there is an 'external database' option in the setup utility, which should generate something like this:

```
###################################
# Database settings
###################################
DB_FLAVOR=postgresql
DB_USER=dbuser
DB_PW=dbpwd
DB_HOST=dburl
DB_NAME=dbname
```

**Comment by guysoft** [comment]
Set that up, however I still seem to get internal server error when setting up http.
I guess I will have to test on x86_64/amd64 before, and if it works build the images for arm64.
