### ISSUE TITLE
Open Relay using IPv6, crashing with IPv4

### ISSUE THREAD

**Issue by p4ck3t0** [Mailu/Mailu#1713]
### Checking Mailu 1.7 for a open relay using nmap IPv4

```bash
nmap -4 --script smtp-open-relay.nse -p 25,465,587 -v <DOMAIN>
```
In the docker-compose logs I see some python errors:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/mailu/internal/views/postfix.py", line 56, in postfix_sender_access
    localpart, domain_name = models.Email.resolve_domain(sender)
  File "/app/mailu/models.py", line 263, in resolve_domain
    alternative = Alternative.query.get(domain_name)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1069, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3275, in one
    ret = self.one_or_none()
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
172.24.0.7 - - [23/Dec/2020:22:15:43 +0000] "GET /internal/postfix/sender/access/antispam@%5B78.46.239.192%5D HTTP/1.1" 500 290 "-" "Python/3.7 aiohttp/3.7.3"
    distilled_params,
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 719, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1201, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 30, in process_bind_param
    return idna.encode(value).decode("ascii").lower()
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 358, in encode
    s = alabel(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 270, in alabel
    ulabel(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 304, in ulabel
    check_label(label)
  File "/usr/lib/python3.7/site-packages/idna/core.py", line 261, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
sqlalchemy.exc.StatementError: (idna.core.InvalidCodepoint) Codepoint U+005B at position 1 of '[78' not allowed
```
Nmap gives this:
```
...
PORT    STATE SERVICE
25/tcp  open  smtp
|_smtp-open-relay: Server doesn't seem to be an open relay, all tests failed
465/tcp open  smtps
|_smtp-open-relay: Server isn't an open relay, authentication needed
587/tcp open  submission
|_smtp-open-relay: Server isn't an open relay, authentication needed
...
```

### When using nmap with IPv6 mailu acts a open relay without any error:

```bash
nmap -6 --script smtp-open-relay.nse -p 25,465,587 -v <DOMAIN>
...
PORT    STATE SERVICE
25/tcp  open  smtp
| smtp-open-relay: Server is an open relay (3/16 tests)
|  MAIL FROM:<> -> RCPT TO:<relaytest@nmap.scanme.org>
|  MAIL FROM:<antispam@nmap.scanme.org> -> RCPT TO:<relaytest@nmap.scanme.org>
|_ MAIL FROM:<antispam@<DOMAIN>> -> RCPT TO:<relaytest@nmap.scanme.org>
465/tcp open  smtps
|_smtp-open-relay: Server isn't an open relay, authentication needed
587/tcp open  submission
|_smtp-open-relay: Server isn't an open relay, authentication needed
...
```

### How to fix the open relay on IPv6:

* Edit the postfix main.cf
* Replace the line `mynetworks = 127.0.0.1/32 [::1]/128 {{ SUBNET }} {{ RELAYNETS }}` with `mynetworks = 127.0.0.1/32 [::1]/128`
* restart postfix

After the fix, IPv4 still throws errors and remains the same :(. But when using IPv6 I get:

```bash
nmap -6 --script smtp-open-relay.nse -p 25,465,587 -v <DOMAIN>
...
PORT    STATE SERVICE
25/tcp  open  smtp
|_smtp-open-relay: Server doesn't seem to be an open relay, all tests failed
465/tcp open  smtps
|_smtp-open-relay: Server isn't an open relay, authentication needed
587/tcp open  submission
|_smtp-open-relay: Server isn't an open relay, authentication needed
...
```

So no IPv6 open Relay anymore.

**Comment by zoh48gz04** [comment]
Experiencing this too, please fix.
