### ISSUE TITLE
Something broke on master & 1.7 admin

### ISSUE THREAD

**Issue by ktechmidas** [Mailu/Mailu#1757]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x ] Check if no issue or pull-request for this already exists.
- [x ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- x[ ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- x[ ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [ x] kubernetes
 - [ ] docker swarm

## Description
Hi all, just wanted to let you know something has broken on admin, just tried to start a new mailu server today and had the following issue on admin when using either "master" or "1.7"

bash-5.0# curl -f -L http://localhost/ui/login?next=ui.index
curl: (7) Failed to connect to localhost port 80: Connection refused

bash-5.0# /start.py
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try "flask --help" for help.

Error: No such command "mailu".
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: Could not import "mailu".
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 60, in __init__
    self.setup(app)
  File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 120, in setup
    self.app.wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'mailu'

## Replication Steps
Start a new mailu server in kubernetes using either 1.7 or master tags.

## Expected behaviour
Expect the admin server to be listening on port 80

**Comment by ktechmidas** [comment]
Aight, ignore me... I think it's something I've done
