### ISSUE TITLE
issues with python let'sencrypt: unhandled traceback to openssl.py

### ISSUE THREAD

**Issue by moumoku** [Mailu/Mailu#1799]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [☑] Check if no issue or pull-request for this already exists.
- [☑] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [☑] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [☑] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [☑] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
$> docker ps -a | grep mailu
140b09d4b09c    mailu/roundcube:1.7    "docker-php-entrypoi…"    2 weeks ago    Up 2 days (healthy)    80/tcp
$> grep MAILU_VERSION docker-compose.yml mailu.env
```
c355d1f3515e   mailu/roundcube:1.7            "docker-php-entrypoi…"   6 minutes ago   Up 5 minutes (healthy)         80/tcp

docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}

## Description
Further explain the bug in a few words. It should be clear what the unexpected behaviour is.  Share it in an easy-to-understand language.
I'm unable to get a cert, due to some python error and am getting 403s as a result

## Replication Steps
Steps for replicating your issue
Deploy as part of an lsio stack (swag, mariadb, ddclient (one for mailu, and one for the main website), and of course mailu all in the same docker-compose.yml, and using swag (nginx) as a reverse proxy.

## Expected behaviour
Explain what results you expected - be as specific as possible. Just saying "it doesn’t work as expected" is not useful. It's also helpful to describe what you actually experienced.
I'd expected to get a cert and be able to at least get into the admin page.

## Logs
Often it is very useful to include log fragments of the involved component. You can get the logs via `docker logs <container name> --tail 1000`. For example for the admin container:
`docker logs mailu_admin_1 --tail 1000`
or using docker-compose `docker-compose -f /mailu/docker-compose.yml logs --tail 1000 admin`
If you can find the relevant section, please share only the parts that seem relevant. If you have any logs, please enclose them in code tags, like so:
/var/log/letsencrypt/letsencrypt.log
````markdown
```
2021-04-11 10:30:13,322:DEBUG:certbot.main:certbot version: 0.35.1
2021-04-11 10:30:13,323:DEBUG:certbot.main:Arguments: ['-n', '--agree-tos', '-d', 'artbymoumoku.org, mail.artbymoumoku.org', '-m', 'admin@artbymoumoku.org', '--standalone', '--cert-name', 'mailu', '--preferred-challenges', 'http', '--http-01-port', '8008', '--keep-until-expiring', '--rsa-key-size', '4096', '--config-dir', '/certs/letsencrypt', '--post-hook', '/config.py']
2021-04-11 10:30:13,323:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-04-11 10:30:13,350:DEBUG:certbot.log:Root logging level set at 20
2021-04-11 10:30:13,351:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-04-11 10:30:13,352:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2021-04-11 10:30:13,360:DEBUG:certbot.plugins.selection:Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f2fa9fd8b10>
Prep: True
2021-04-11 10:30:13,361:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7f2fa9fd8b10> and installer None
2021-04-11 10:30:13,361:INFO:certbot.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2021-04-11 10:30:14,206:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-04-11 10:30:14,211:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-04-11 10:30:14,256:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.35.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.7/site-packages/certbot/main.py", line 1379, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.7/site-packages/certbot/main.py", line 1246, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3.7/site-packages/certbot/main.py", line 606, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3.7/site-packages/certbot/main.py", line 522, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python3.7/site-packages/certbot/client.py", line 177, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python3.7/site-packages/certbot/client.py", line 47, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 813, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 1146, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 1095, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 350, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 282, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/usr/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 429, in verify_mode
    _verify_callback
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1103, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 333, in __init__
    "int (*)(int, X509_STORE_CTX *)", wrapper)
SystemError: <method 'callback' of 'CompiledFFI' objects> returned NULL without setting an error
2021-04-11 10:30:14,261:ERROR:certbot.log:An unexpected error occurred:
```
````

$ sudo docker logs containers_front_1
````markdown
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Missing cert or key file, disabling TLS
2021/04/11 10:30:13 [notice] 1#1: using the "epoll" event method
2021/04/11 10:30:13 [notice] 1#1: nginx/1.16.1
2021/04/11 10:30:13 [notice] 1#1: OS: Linux 4.19.0-14-amd64
2021/04/11 10:30:13 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/04/11 10:30:13 [notice] 1#1: start worker processes
2021/04/11 10:30:13 [notice] 1#1: start worker process 12
2021/04/11 10:30:13 [notice] 1#1: start worker process 13
2021/04/11 10:30:13 [notice] 1#1: start worker process 14
2021/04/11 10:30:13 [notice] 1#1: start worker process 15
An unexpected error occurred:
SystemError: <method 'callback' of 'CompiledFFI' objects> returned NULL without setting an error
Please see the logfiles in /var/log/letsencrypt for more details.
127.0.0.1 - - [11/Apr/2021:10:30:37 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:30:37 [info] 12#12: *1 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:31:07 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:31:07 [info] 12#12: *2 client 127.0.0.1 closed keepalive connection
2021/04/11 10:31:24 [info] 12#12: *3 client sent invalid method while reading client request line, client: 10.0.0.238, server: , request: "�1�1�T)�>8R`y�Dx��5Gf泧j� �'X�,UW]>|�f߀�<���mS�ȑ����$�+�/̨̩�,�0�"
10.0.0.238 - - [11/Apr/2021:10:31:24 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x031\x9C1\x80T)\x02\x06\xE1>8R`y\xA1Dx\xAB\xA45Gf\xE6\xB3\xA7\x1B\xC9\x08\x0E\x01j\xDD \x8B'X\xD8,UW]>|\xB4\x06f\xDF\x80\xC4<\xE7\x8B\xC0\x07mS\x06\xAD\xC8\x91\x99\xA7\xA8\x12\xEF\x00$\x13\x01\x13\x03\x13\x02\xC0+\xC0/\xCC\xA9\xCC\xA8\xC0,\xC00\xC0" 400 150 "-" "-"
2021/04/11 10:31:24 [info] 12#12: *3 recv() failed (104: Connection reset by peer) while reading client request line, client: 10.0.0.238, server: , request: "�1�1�T)�>8R`y�Dx��5Gf泧j� �'X�,UW]>|�f߀�<���mS�ȑ����$�+�/̨̩�,�0�"
127.0.0.1 - - [11/Apr/2021:10:31:37 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:31:37 [info] 12#12: *4 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:32:07 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:32:07 [info] 12#12: *5 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:32:37 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:32:37 [info] 12#12: *6 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:33:07 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:33:07 [info] 12#12: *7 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:33:38 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:33:38 [info] 12#12: *8 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:34:08 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:34:08 [info] 12#12: *9 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:34:38 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:34:38 [info] 12#12: *10 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:35:08 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:35:08 [info] 12#12: *11 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:35:38 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:35:38 [info] 12#12: *12 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:36:08 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:36:08 [info] 12#12: *13 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:36:38 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:36:38 [info] 12#12: *14 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:37:08 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:37:08 [info] 12#12: *15 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:37:39 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:37:39 [info] 12#12: *16 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:38:09 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:38:09 [info] 12#12: *17 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:38:39 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:38:39 [info] 12#12: *18 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:39:09 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:39:09 [info] 12#12: *19 client 127.0.0.1 closed keepalive connection
2021/04/11 10:39:39 [info] 12#12: *20 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:39:39 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
127.0.0.1 - - [11/Apr/2021:10:40:09 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:40:09 [info] 12#12: *21 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:40:39 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:40:39 [info] 12#12: *22 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:41:10 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:41:10 [info] 12#12: *23 client 127.0.0.1 closed keepalive connection
2021/04/11 10:41:40 [info] 12#12: *24 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:41:40 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
127.0.0.1 - - [11/Apr/2021:10:42:10 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:42:10 [info] 12#12: *25 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:42:40 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:42:40 [info] 12#12: *26 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:43:10 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:43:10 [info] 12#12: *27 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [11/Apr/2021:10:43:40 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.66.0"
2021/04/11 10:43:40 [info] 12#12: *28 client 127.0.0.1 closed keepalive connection
```
````

**Comment by moumoku** [comment]
As a side note, the other containters unrelated to mailu are functioning without a hitch as of yet.
