### ISSUE TITLE
Make spam filter optional

### ISSUE THREAD

**Issue by HarHarLinks** [Mailu/Mailu#1981]
## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.8

## Description
I am trying to set up an easy IMAP storage without any need to send or receive mail. Essentially an archive server. For this a lot of features are not needed. From the generated docker-compose.yml I tried commenting out the smtp container and ports and also antispam container. Turns out when antispam does not exist (can't resolve its name), then the config.py script for the nginx config crashes and nothing ever starts up.

## Replication Steps
see above

## Expected behaviour
Optional (default=on) spam filter. This could be hidden in advanced settings, requiring you to modify docker-compose files etc.

## Logs
Your logs here!
```
Attaching to mailu_front_1
front_1     | Saving debug log to /var/log/letsencrypt/letsencrypt.log
front_1     | Account registered.
front_1     | Requesting a certificate for mydomain
front_1     | 
front_1     | Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
front_1     |   Domain: mydomain
front_1     |   Type:   unauthorized
front_1     |   Detail: Invalid response from http://mydomain/.well-known/acme-challenge/redacted [myIP]: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><cen"
front_1     | 
front_1     | Hint: The Certificate Authority couldn't exterally verify that the standalone plugin completed the required http-01 challenges. Ensure the plugin is configured correctly and that the changes it makes are accessible from the internet.
front_1     | 
front_1     | Traceback (most recent call last):
front_1     |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 407, in __call__
front_1     |     result = fn(*args, **kwargs)
front_1     |   File "/usr/lib/python3.9/site-packages/socrate/system.py", line 12, in resolve_hostname
front_1     |     return socket.gethostbyname(hostname)
front_1     | socket.gaierror: [Errno -2] Name does not resolve
front_1     | 
front_1     | The above exception was the direct cause of the following exception:
front_1     | 
front_1     | Traceback (most recent call last):
front_1     |   File "/config.py", line 18, in <module>
front_1     |     args["ANTISPAM_WEBUI_ADDRESS"] = system.get_host_address_from_environment("ANTISPAM_WEBUI", "antispam:11334")
front_1     |   File "/usr/lib/python3.9/site-packages/socrate/system.py", line 32, in get_host_address_from_environment
front_1     |     return resolve_address(environ.get("HOST_{}".format(name), default))
front_1     |   File "/usr/lib/python3.9/site-packages/socrate/system.py", line 20, in resolve_address
front_1     |     ip_address = resolve_hostname(hostname)
front_1     |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 324, in wrapped_f
front_1     |     return self(f, *args, **kw)
front_1     |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 404, in __call__
front_1     |     do = self.iter(retry_state=retry_state)
front_1     |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 361, in iter
front_1     |     raise retry_exc from fut.exception()
front_1     | tenacity.RetryError: RetryError[<Future at 0x7ff9d4742b80 state=finished raised gaierror>]
```

**Comment by HarHarLinks** [comment]
In fact it seems to be similar with the admin UI depending on smtp
```
admin_1     | Traceback (most recent call last):
admin_1     |   File "/usr/bin/gunicorn", line 8, in <module>
admin_1     |     sys.exit(run())
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
admin_1     |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/app/base.py", line 223, in run
admin_1     |     super(Application, self).run()
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
admin_1     |     Arbiter(self).run()
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/arbiter.py", line 60, in __init__
admin_1     |     self.setup(app)
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/arbiter.py", line 120, in setup
admin_1     |     self.app.wsgi()
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
admin_1     |     self.callable = self.load()
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
admin_1     |     return self.load_wsgiapp()
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
admin_1     |     return util.import_app(self.app_uri)
admin_1     |   File "/usr/lib/python3.9/site-packages/gunicorn/util.py", line 362, in import_app
admin_1     |     app = eval(obj, vars(mod))
admin_1     |   File "<string>", line 1, in <module>
admin_1     |   File "/app/mailu/__init__.py", line 60, in create_app
admin_1     |     return create_app_from_config(config)
admin_1     |   File "/app/mailu/__init__.py", line 22, in create_app_from_config
admin_1     |     config.init_app(app)
admin_1     |   File "/app/mailu/configuration.py", line 121, in init_app
admin_1     |     self.resolve_hosts()
admin_1     |   File "/app/mailu/configuration.py", line 101, in resolve_hosts
admin_1     |     self.config["AUTHSMTP_ADDRESS"] = self.get_host_address("AUTHSMTP")
admin_1     |   File "/app/mailu/configuration.py", line 96, in get_host_address
admin_1     |     return system.resolve_address(self.config['HOST_{}'.format(name)])
admin_1     |   File "/usr/lib/python3.9/site-packages/socrate/system.py", line 19, in resolve_address
admin_1     |     ip_address = resolve_hostname(hostname)
admin_1     |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 292, in wrapped_f
admin_1     |     return self.call(f, *args, **kw)
admin_1     |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 358, in call
admin_1     |     do = self.iter(retry_state=retry_state)
admin_1     |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 332, in iter
admin_1     |     six.raise_from(retry_exc, fut.exception())
admin_1     |   File "<string>", line 3, in raise_from
admin_1     | tenacity.RetryError: RetryError[<Future at 0x7f76edbb6550 state=finished raised gaierror>]
```

**Comment by Diman0** [comment]
The antispam container is a mandatory component. Mailu is not made for this purpose. For only IMAP storage you are better of using a different solution than Mailu.
