### ISSUE TITLE
Adding emoji domain in the admin UI will result in 500 status code

### ISSUE THREAD

**Issue by henry-bao** [Mailu/Mailu#2043]
## Before you open your issue
- [ ] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
master

## Description
Entering an emoji domain such as  `👌🏼.to` or `xn--nn8h5e.to` in the admin UI as a new mail domain will result in a 500 status code, and the domain will not be added

## Replication Steps
Try add `👌🏼.to` or `xn--nn8h5e.to` as a new domain in the admin UI

## Expected behaviour
The domain should be added without resulting in an error

## Logs
````markdown
admin_1      | The above exception was the direct cause of the following exception:
admin_1      |
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 2292, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1815, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1718, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1813, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/lib/python3.9/site-packages/flask_login/utils.py", line 261, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 36, in wrapper
admin_1      |     return callback(function, args, kwargs, (), {})
admin_1      |   File "/app/mailu/ui/access.py", line 19, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/views/domains.py", line 22, in domain_create
admin_1      |     conflicting_domain = models.Domain.query.get(form.name.data)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 959, in get
admin_1      |     return self._get_impl(ident, loading.load_on_pk_identity)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 1069, in _get_impl
admin_1      |     return db_load_fn(self, primary_key_identity)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
admin_1      |     return q.one()
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3275, in one
admin_1      |     ret = self.one_or_none()
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
admin_1      |     ret = list(self)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
admin_1      |     return self._execute_and_instances(context)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
admin_1      |     result = conn.execute(querycontext.statement, self._params)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 988, in execute
admin_1      |     return meth(self, multiparams, params)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
admin_1      |     return connection._execute_clauseelement(self, multiparams, params)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
admin_1      |     ret = self._execute_context(
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1181, in _execute_context
admin_1      |     self._handle_dbapi_exception(
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
admin_1      |     util.raise_from_cause(sqlalchemy_exception, exc_info)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
admin_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
admin_1      |     raise value.with_traceback(tb)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
admin_1      |     context = constructor(dialect, self, conn, *args)
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 738, in _init_compiled
admin_1      |     param = dict(
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 741, in <genexpr>
admin_1      |     processors[key](compiled_params[key])
admin_1      |   File "/usr/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1201, in process
admin_1      |     return process_param(value, dialect)
admin_1      |   File "/app/mailu/models.py", line 44, in process_bind_param
admin_1      |     return idna.encode(value.lower()).decode('ascii')
admin_1      |   File "/usr/lib/python3.9/site-packages/idna/core.py", line 358, in encode
admin_1      |     s = alabel(label)
admin_1      |   File "/usr/lib/python3.9/site-packages/idna/core.py", line 281, in alabel
admin_1      |     check_label(label)
admin_1      |   File "/usr/lib/python3.9/site-packages/idna/core.py", line 261, in check_label
admin_1      |     raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
admin_1      | sqlalchemy.exc.StatementError: (idna.core.InvalidCodepoint) Codepoint U+1F44C at position 1 of '👌🏼' not allowed
admin_1      | [SQL: SELECT domain.created_at AS domain_created_at, domain.updated_at AS domain_updated_at, domain.comment AS domain_comment, domain.name AS domain_name, domain.max_users AS domain_max_users, domain.max_aliases AS domain_max_aliases, domain.max_quota_bytes AS domain_max_quota_bytes, domain.signup_enabled AS domain_signup_enabled
admin_1      | FROM domain
admin_1      | WHERE domain.name = %(param_1)s]
admin_1      | [parameters: [{'%(140621914643664 param)s': '👌🏼.to'}]]
admin_1      | [2021-11-06 22:20:33,947] ERROR in app: Exception on /admin/domain/create [POST]
````

**Comment by ghostwheel42** [comment]
Hi.
According to RFC 5891 symbols are forbidden to use in Simson names (see appendix A.3): https://datatracker.ietf.org/doc/html/rfc5891#appendix-A

We are using the Python idna library which implements idna according to the RFC (see this issue:
https://github.com/kjd/idna/issues/61#issuecomment-380259117 )

But we should probably catch the exception and display an error message in the frontend.

**Comment by henry-bao** [comment]
Oh, I see, thanks for the info. Cheers
