### ISSUE TITLE
Strange behaviour after restart.

### ISSUE THREAD

**Issue by richardbeumer** [Mailu/Mailu#2162]
### Environment
 - [ ] docker-compose
 - [x] kubernetes
 - [ ] docker swarm

### Versions
1.8

## Description
After restarting my pods I suddenly get below error when trying to login. I suspect it's an issue in my database but I'm not sure. Please advise where to look further

## Logs
```
[2022-01-13 19:19:54,943] ERROR in app: Exception on /internal/auth/email [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/mailu/internal/views/auth.py", line 24, in nginx_authentication
    headers = nginx.handle_authentication(flask.request.headers)
  File "/app/mailu/internal/nginx.py", line 59, in handle_authentication
    if (token.check_password(password) and
  File "/app/mailu/models.py", line 499, in check_password
    return hash.sha256_crypt.verify(password, self.password)
  File "/usr/lib/python3.9/site-packages/passlib/utils/handlers.py", line 757, in verify
    self = cls.from_string(hash, **context)
  File "/usr/lib/python3.9/site-packages/passlib/handlers/sha2_crypt.py", line 307, in from_string
    raise uh.exc.InvalidHashError(cls)
ValueError: not a valid sha256_crypt hash
```

**Comment by richardbeumer** [comment]
Apperently my version was upgraded to `1.9`. I was using the `master` tag so all my containers where updated when restarted.
When moving back to `1.8` I got above error. So I tried upgrading to `1.9` when I got an DNSSEC error: `CRITICAL:root:Your DNS resolver at xxx.xxx.xxx.xxx isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.`

I moved to `1.9.7` and everything is working fine now.
