### ISSUE TITLE
Kubernetes "WORKER TIMEOUT"

### ISSUE THREAD

**Issue by mathieumagalhaes** [Mailu/Mailu#221]
I'm trying to make Mailu work on Kubernetes (latest version). The deployment based on the wiki's wiki's [YAML](https://github.com/Mailu/Mailu/wiki/Running-on-Kubernetes) file (slightly modified for persistent storage etc.) works and shows no sign of failure. I did add some ingress rules that way I can access the admin panel through a domain.

Everything seems to be working, I can access the admin panel's login page, but once I try to login I get a **502 Bad Gateway** error.

The admin panel's container is showing following logs:

`[2017-07-12` 16:58:35 +0000] [10] [CRITICAL] WORKER TIMEOUT `(pid:23)`
`[2017-07-12 16:58:36 +0000] [28] [INFO] Booting worker with pid: 28`

Not much info to go on next.

I first thought it was because of the nginx controller timeouts times.
I increased the timeouts but this did not change the situation.

Any idea?

PS. Side question:
is the SECRET_KEY value of the admin panel environment (see wiki's [YAML](https://github.com/Mailu/Mailu/wiki/Running-on-Kubernetes)) also the password of your admin account?

**Comment by mathieumagalhaes** [comment]
Investigating further I did look over this exception on startup of the Mailu/admin container.
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
  File "manage.py", line 74, in <module>
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 247, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 421, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
```

**Comment by kaiyou** [comment]
Side question: no, the secret key is only used for Flask security purposes (session cookie, password storage, etc.)

Regarding the exception, indeed the admin container fails to start in the first place. Are you running multiple admin containers? I am afraid that the current database scheme based on SQLite will not behave well with multiple read/write workers trying to migrate concurrently during startup.

**Comment by kaiyou** [comment]
I am closing this bug since there is no follow-up.
