### ISSUE TITLE
Sass error when trying to build admin

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#2220]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9.12

## Description
When trying to build admin, I get the following error since 1.9.12 although I don't see any change about that
 
```
#17 [assets 6/6] RUN set -eu  && sed -i 's/#007bff/#55a5d9/' node_modules/admin-lte/build/scss/_bootstrap-variables.scss  && for l in ca da de:de_de en:en-gb es:es_es eu fr:fr_fr he hu is it:it_it ja nb_NO:no_nb nl:nl_nl pl pt:pt_pt ru sv:sv_se zh; do       cp node_modules/datatables.net-plugins/i18n/${l#*:}.json assets/${l%:*}.json;     done  && node_modules/.bin/webpack-cli --color
#17 15.70 assets by status 3.56 MiB [cached] 39 assets
#17 15.70 Entrypoint app = app.css app.js 20 auxiliary assets
#17 15.70 Entrypoint vendor = vendor.css vendor.js
#17 15.70 orphan modules 176 KiB (javascript) 2.79 MiB (asset) 4.68 KiB (runtime) [orphan] 65 modules
#17 15.70 runtime modules 5.47 KiB 9 modules
#17 15.70 cacheable modules 1.41 MiB (javascript) 114 KiB (asset) 83 KiB (css/mini-extract)
#17 15.70   modules by layer 1.41 MiB (javascript) 114 KiB (asset)
#17 15.70     modules by path ./assets/ 86.5 KiB (javascript) 114 KiB (asset) 23 modules
#17 15.70     modules by path ./node_modules/ 1.32 MiB
#17 15.70       modules by path ./node_modules/admin-lte/ 496 KiB 8 modules
#17 15.70       modules by path ./node_modules/clipboard/dist/*.js 46.8 KiB 2 modules
#17 15.70       + 4 modules
#17 15.70   css modules 83 KiB
#17 15.70     css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/admin-lte/plugins/fontawesome-free/css/all.min.css 56.2 KiB [built] [code generated]
#17 15.70     css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/admin-lte/plugins/select2/css/select2.min.css 14.6 KiB [built] [code generated]
#17 15.70     css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css 7.32 KiB [built] [code generated]
#17 15.70     css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/admin-lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css 4.19 KiB [built] [code generated]
#17 15.70     css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./assets/app.css 717 bytes [built] [code generated]
#17 15.70 
#17 15.70 ERROR in ./node_modules/admin-lte/build/scss/adminlte.scss (./node_modules/admin-lte/build/scss/adminlte.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/admin-lte/build/scss/adminlte.scss)
#17 15.70 Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
#17 15.70 SassError: Top-level selectors may not contain the parent selector "&".
#17 15.70   ╷
#17 15.70 7 │   &.bg-#{$name} {
#17 15.70   │   ^^^^^^^^^^^^^^
#17 15.70   ╵
#17 15.70   node_modules/admin-lte/build/scss/mixins/_backgrounds.scss 7:3   background-variant()
#17 15.70   node_modules/admin-lte/build/scss/_colors.scss 7:3               @import
#17 15.70   node_modules/admin-lte/build/scss/parts/_miscellaneous.scss 9:9  @import
#17 15.70   node_modules/admin-lte/build/scss/adminlte.scss 25:9             root stylesheet
#17 15.70 SassError: SassError: Top-level selectors may not contain the parent selector "&".
#17 15.70   ╷
#17 15.70 7 │   &.bg-#{$name} {
#17 15.70   │   ^^^^^^^^^^^^^^
#17 15.70   ╵
#17 15.70   node_modules/admin-lte/build/scss/mixins/_backgrounds.scss 7:3   background-variant()
#17 15.70   node_modules/admin-lte/build/scss/_colors.scss 7:3               @import
#17 15.70   node_modules/admin-lte/build/scss/parts/_miscellaneous.scss 9:9  @import
#17 15.70   node_modules/admin-lte/build/scss/adminlte.scss 25:9             root stylesheet
#17 15.70     at /node_modules/sass-loader/dist/index.js:54:16
#17 15.70     at Function.call$2 (/node_modules/sass/sass.dart.js:92646:16)
#17 15.70     at _render_closure1.call$2 (/node_modules/sass/sass.dart.js:81147:12)
#17 15.70     at _RootZone.runBinary$3$3 (/node_modules/sass/sass.dart.js:27268:18)
#17 15.70     at _FutureListener.handleError$1 (/node_modules/sass/sass.dart.js:25818:19)
#17 15.70     at _Future__propagateToListeners_handleError.call$0 (/node_modules/sass/sass.dart.js:26116:49)
#17 15.70     at Object._Future__propagateToListeners (/node_modules/sass/sass.dart.js:4539:77)
#17 15.70     at _Future._completeError$2 (/node_modules/sass/sass.dart.js:25948:9)
#17 15.70     at _AsyncAwaitCompleter.completeError$2 (/node_modules/sass/sass.dart.js:25602:12)
#17 15.70     at Object._asyncRethrow (/node_modules/sass/sass.dart.js:4338:17)
#17 15.70  @ ./node_modules/admin-lte/build/scss/adminlte.scss
#17 15.70  @ ./assets/vendor.js 4:0-44
#17 15.70 
#17 15.70 ERROR in ./node_modules/admin-lte/build/scss/adminlte.scss
#17 15.70 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
#17 15.70 HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
#17 15.70 SassError: Top-level selectors may not contain the parent selector "&".
#17 15.70   ╷
#17 15.70 7 │   &.bg-#{$name} {
#17 15.70   │   ^^^^^^^^^^^^^^
#17 15.70   ╵
#17 15.70   node_modules/admin-lte/build/scss/mixins/_backgrounds.scss 7:3   background-variant()
#17 15.70   node_modules/admin-lte/build/scss/_colors.scss 7:3               @import
#17 15.70   node_modules/admin-lte/build/scss/parts/_miscellaneous.scss 9:9  @import
#17 15.70   node_modules/admin-lte/build/scss/adminlte.scss 25:9             root stylesheet
#17 15.70     at tryRunOrWebpackError (/node_modules/webpack/lib/HookWebpackError.js:88:9)
#17 15.70     at __webpack_require_module__ (/node_modules/webpack/lib/Compilation.js:5023:12)
#17 15.70     at __webpack_require__ (/node_modules/webpack/lib/Compilation.js:4980:18)
#17 15.70     at /node_modules/webpack/lib/Compilation.js:5051:20
#17 15.70     at symbolIterator (/node_modules/neo-async/async.js:3485:9)
#17 15.70     at done (/node_modules/neo-async/async.js:3527:9)
#17 15.70     at Hook.eval [as callAsync] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
#17 15.70     at /node_modules/webpack/lib/Compilation.js:4958:43
#17 15.70     at symbolIterator (/node_modules/neo-async/async.js:3482:9)
#17 15.70     at timesSync (/node_modules/neo-async/async.js:2297:7)
#17 15.70 -- inner error --
#17 15.70 Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
#17 15.70 SassError: Top-level selectors may not contain the parent selector "&".
#17 15.70   ╷
#17 15.70 7 │   &.bg-#{$name} {
#17 15.70   │   ^^^^^^^^^^^^^^
#17 15.70   ╵
#17 15.70   node_modules/admin-lte/build/scss/mixins/_backgrounds.scss 7:3   background-variant()
#17 15.70   node_modules/admin-lte/build/scss/_colors.scss 7:3               @import
#17 15.70   node_modules/admin-lte/build/scss/parts/_miscellaneous.scss 9:9  @import
#17 15.70   node_modules/admin-lte/build/scss/adminlte.scss 25:9             root stylesheet
#17 15.70     at Object.<anonymous> (/node_modules/css-loader/dist/cjs.js!/node_modules/sass-loader/dist/cjs.js!/node_modules/admin-lte/build/scss/adminlte.scss:1:7)
#17 15.70     at /node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:432:11
#17 15.70     at Hook.eval [as call] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
#17 15.70     at /node_modules/webpack/lib/Compilation.js:5025:39
#17 15.70     at tryRunOrWebpackError (/node_modules/webpack/lib/HookWebpackError.js:83:7)
#17 15.70     at __webpack_require_module__ (/node_modules/webpack/lib/Compilation.js:5023:12)
#17 15.70     at __webpack_require__ (/node_modules/webpack/lib/Compilation.js:4980:18)
#17 15.70     at /node_modules/webpack/lib/Compilation.js:5051:20
#17 15.70     at symbolIterator (/node_modules/neo-async/async.js:3485:9)
#17 15.70     at done (/node_modules/neo-async/async.js:3527:9)
#17 15.70 
#17 15.70 Generated code for /node_modules/css-loader/dist/cjs.js!/node_modules/sass-loader/dist/cjs.js!/node_modules/admin-lte/build/scss/adminlte.scss
#17 15.70 1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Top-level selectors may not contain the parent selector \"&\".\n  ╷\n7 │   &.bg-#{$name} {\n  │   ^^^^^^^^^^^^^^\n  ╵\n  node_modules/admin-lte/build/scss/mixins/_backgrounds.scss 7:3   background-variant()\n  node_modules/admin-lte/build/scss/_colors.scss 7:3               @import\n  node_modules/admin-lte/build/scss/parts/_miscellaneous.scss 9:9  @import\n  node_modules/admin-lte/build/scss/adminlte.scss 25:9             root stylesheet");
#17 15.70  @ ./assets/vendor.js 4:0-44
#17 15.70 
#17 15.70 webpack 5.68.0 compiled with 2 errors in 14241 ms
#17 ERROR: process "/bin/sh -c set -eu  && sed -i 's/#007bff/#55a5d9/' node_modules/admin-lte/build/scss/_bootstrap-variables.scss  && for l in ca da de:de_de en:en-gb es:es_es eu fr:fr_fr he hu is it:it_it ja nb_NO:no_nb nl:nl_nl pl pt:pt_pt ru sv:sv_se zh; do       cp node_modules/datatables.net-plugins/i18n/${l#*:}.json assets/${l%:*}.json;     done  && node_modules/.bin/webpack-cli --color" did not complete successfully: exit code: 1
```

## Replication Steps
I'm using @Erriez multi arch build but I do get the issue when building with each platform one by one (amd64, arm64 & armv7)
I don't think it's directly linked to 1.9.12 as I was able to pass this command in previous builds so maybe a package dependency has been changed w/o notice? (The build was working fine also with 1.9.10)
I found the same issue at different places on the internet like this one: https://github.com/sass/sass/issues/1873 so it seems to be a very old thing and it looks like admin-lte package contains this issue eg line 7 of https://github.com/ColorlibHQ/AdminLTE/blob/master/build/scss/mixins/_backgrounds.scss ==> maybe I need to create the issue in AdminLTE repo?

**Comment by yogitea** [comment]
I get this when building 1.9 and master branch.
