### ISSUE TITLE
https://setup.mailu.io return 404

### ISSUE THREAD

**Issue by jerrita** [Mailu/Mailu#2249]
As follows

<img width="903" alt="image" src="https://user-images.githubusercontent.com/28153001/154723989-64844f8c-4310-4aef-a54d-c8dab5bf6b81.png">

**Comment by J-eremy** [comment]
Same issue, want to try it but cant.

**Comment by Diman0** [comment]
```
Attaching to setup_stable_1
stable_1       | Traceback (most recent call last):
stable_1       |   File "/usr/bin/gunicorn", line 8, in <module>
stable_1       |     sys.exit(run())
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/app/[wsgiapp.py](http://wsgiapp.py/)", line 61, in run
stable_1       |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/app/[base.py](http://base.py/)", line 223, in run
stable_1       |     super(Application, self).run()
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/app/[base.py](http://base.py/)", line 72, in run
stable_1       |     Arbiter(self).run()
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/[arbiter.py](http://arbiter.py/)", line 60, in __init__
stable_1       |     self.setup(app)
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/[arbiter.py](http://arbiter.py/)", line 120, in setup
stable_1       |     [self.app](http://self.app/).wsgi()
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/app/[base.py](http://base.py/)", line 67, in wsgi
stable_1       |     self.callable = self.load()
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/app/[wsgiapp.py](http://wsgiapp.py/)", line 52, in load
stable_1       |     return self.load_wsgiapp()
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/app/[wsgiapp.py](http://wsgiapp.py/)", line 41, in load_wsgiapp
stable_1       |     return util.import_app([self.app](http://self.app/)_uri)
stable_1       |   File "/usr/lib/python3.9/site-packages/gunicorn/[util.py](http://util.py/)", line 350, in import_app
stable_1       |     __import__(module)
stable_1       |   File "/app/[main.py](http://main.py/)", line 1, in <module>
stable_1       |     from server import app, build_app
stable_1       |   File "/app/[server.py](http://server.py/)", line 1, in <module>
stable_1       |     import flask
stable_1       |   File "/usr/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
stable_1       |     from .app import Flask, Request, Response
stable_1       |   File "/usr/lib/python3.9/site-packages/flask/[app.py](http://app.py/)", line 25, in <module>
stable_1       |     from . import cli, json
stable_1       |   File "/usr/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
stable_1       |     from itsdangerous import json as _json
stable_1       | ImportError: cannot import name 'json' from 'itsdangerous' (/usr/lib/python3.9/site-packages/itsdangerous/__init__.py)
```

I suspect setup has a dependency that is not pinned and a breaking update was pulled. I will have a look.
