### ISSUE TITLE
Exceptions in logfile: KeyError: 'WEBMAIL_ADDRESS'

### ISSUE THREAD

**Issue by TerrapinSoftware** [Mailu/Mailu#2327]
### Environment
docker-compose

### Versions
1.9

## Description
I observed several tracebacks in the logs (mailu-admin) because of the error shown below.

## Replication Steps
Unknown

## Expected behaviour
No exceptions in log

## Logs

```
[2022-04-26 09:07:02,615] ERROR in app: Exception on /internal/auth/email [GET]
Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
   File "/app/mailu/internal/views/auth.py", line 19, in nginx_authentication
     utils.limiter.rate_limit_ip(client_ip)
   File "/app/mailu/limiter.py", line 56, in rate_limit_ip
     if ip != app.config['WEBMAIL_ADDRESS']:
 KeyError: 'WEBMAIL_ADDRESS'
```

**Comment by nextgens** [comment]
Can you paste the output of ```docker-compose exec smtp cat /version``` please?

It looks like you aren't running the latest version of Mailu and this has already been addressed.

**Comment by TerrapinSoftware** [comment]
Looks like it is 1.9.2.
