### ISSUE TITLE
Calendar Function on Webmail container

### ISSUE THREAD

**Issue by himuura** [Mailu/Mailu#2342]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [X ] Check if no issue or pull-request for this already exists.
- [ X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
$> docker ps -a | grep mailu --> v1.9

```

## Description
Kolab/Calendar plugin for roundcube breaks the mail function. Mail simply cannot be read.
Anyone has figured out how to install the calendar (or any other calendar plugin) on the webmail container?
I've read the #545 and #2045 cases and it was my assumption that it would be easier to install a calendar plugin other than default (my bad, not the mailu team!). Any chance anyone can give me a hand?

## Replication Steps
install kolab/calendar plugin as per https://github.com/kolab-roundcube-plugins-mirror/calendar

## Expected behaviour
Calendar is working, i can see it. But due to errors, the mail function stopped working, mail cannot be read.

## Logs

````markdown
```
[Tue May 10 17:36:22.252447 2022] [php:error] [pid 29] [client 192.168.203.2:47046] PHP Fatal error:  Uncaught Error: Class "Sabre\\VObject\\Property\\Text" not found in /var/www/html/plugins/libcalendaring/libvcalendar.php:1520\nStack trace:\n#0 /var/www/html/plugins/libcalendaring/libcalendaring.php(158): require_once()\n#1 /var/www/html/plugins/libcalendaring/libcalendaring.php(1170): libcalendaring::get_ical()\n#2 /var/www/html/plugins/calendar/calendar.php(3237): libcalendaring->get_mail_ical_objects()\n#3 /var/www/html/program/lib/Roundcube/rcube_plugin_api.php(513): calendar->mail_messagebody_html()\n#4 /var/www/html/program/include/rcmail_output_html.php(1610): rcube_plugin_api->exec_hook()\n#5 [internal function]: rcmail_output_html->xml_command()\n#6 /var/www/html/program/include/rcmail_output_html.php(1322): preg_replace_callback()\n#7 /var/www/html/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()\n#8 /var/www/html/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()\n#9 /var/www/html/program/actions/mail/show.php(164): rcmail_output_html->send()\n#10 /var/www/html/program/include/rcmail.php(275): rcmail_action_mail_show->run()\n#11 /var/www/html/index.php(283): rcmail->action_handler()\n#12 {main}\n  thrown in /var/www/html/plugins/libcalendaring/libvcalendar.php on line 1520, referer: http://192.168.36.13/webmail/?_task=mail&_mbox=INBOX
```
````

**Comment by himuura** [comment]
Nothing yet...followed roundcube's instructions to install custom plugins on the docker image...no success. I do manage to install it and have a calendar display but it simply break the inbox mails (Oops something went wrong -> it's as far as i got).
What am i missing? I installed the calendar under /var/www/html/plugins, followed all the instructions, installed the node-free (else, it would error on the lessc part of the roundcube's tutorial). Has anyone single soul managed to get this minimally running? Any help would be very much appreciated! The calendar is just one of those functions that big and small companies cannot  "live" without...

**Comment by himuura** [comment]
managed to figure it out! i'm testing it right now.
Here's the solution (as per kolab instructions):

inside the webmail container:
docker exec -it -u root mailu-webmail-1 bash

on the container bash do:
apt update && apt install nano node-less
(i use nano as my prefered editor but you can use vi or vim)

1. Get the source from git

  $ cd /tmp
  $ git clone https://git.kolab.org/diffusion/RPK/roundcubemail-plugins-kolab.git
  $ cd /var/www/html/plugins
  $ cp -r /tmp/roundcubemail-plugins-kolab/plugins/calendar .
  $ cp -r /tmp/roundcubemail-plugins-kolab/plugins/libcalendaring .
  $ cp -r /tmp/roundcubemail-plugins-kolab/plugins/libkolab .

2. Create calendar plugin configuration

  $ cd calendar/
  $ cp config.inc.php.dist config.inc.php
  $ nano config.inc.php (and take a look at the config, change what you need)

3. Initialize the calendar database tables

  $ cd ../../
  $ bin/initdb.sh --dir=plugins/calendar/drivers/database/SQL

4. Build css styles for the Elastic skin

  $ lessc --relative-urls -x plugins/libkolab/skins/elastic/libkolab.less > plugins/libkolab/skins/elastic/libkolab.min.css

5. Enable the calendar plugin

  $ nano config/config.inc.php

Add 'calendar' to the list of active plugins:

  $config['plugins'] = array(
	(...)
	'calendar',
  );
Mine is similar to this:
$config['plugins'] = array('archive','zipdownload','markasjunk','managesieve','enigma','carddav','mailu','calendar','libcalendaring','libkolab');
(note: it's imperative that the libcalendaring and libkolab are in this activation line or it will break the mail functionality)

Now, my issue is with webdav and importing iCal...will keep this updated!

**Comment by himuura** [comment]
Well, there seems to be no way to accept an invitation for an event (calendar). That and i cannot find a way to create a Global Address List (GAL) in the Mailu administration page...

**Comment by himuura** [comment]
Anyone has kolab/calendar working so far?
