### ISSUE TITLE
Certbot ContextualVersionConflict

### ISSUE THREAD

**Issue by n0izn0iz** [Mailu/Mailu#237]
Hey, I had a certbot error with nothing after the "An unexpected error occured:" line, I applied this commit #234 and got this:
```
Generating TLS certificates using Certbot
Error while generating certificates:
An unexpected error occurred:
pkg_resources.ContextualVersionConflict: (idna 2.6 (/usr/local/lib/python3.6/site-packages), Requirement.parse('idna<2.6,>=2.5'), {'requests'})
Please see the logfile '/tmp/tmpoglusc6u' for more details.
```
```
$> cat /tmp/tmpoglusc6u
2017-08-25 09:28:37,082:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/certbot/main.py", line 733, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python3.6/site-packages/certbot/plugins/disco.py", line 203, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python3.6/site-packages/certbot/plugins/disco.py", line 50, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2304, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2327, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 862, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.6 (/usr/local/lib/python3.6/site-packages), Requirement.parse('idna<2.6,>=2.5'), {'requests'})
```
I'm a python newb so not sure how to fix it.

**Comment by n0izn0iz** [comment]
Looks like an upstream issue https://github.com/certbot/certbot/issues/5015

**Comment by n0izn0iz** [comment]
Temporary fix for mailu, I assume the mailu admin container is called `mailu_admin_1`:
`docker exec -i -t mailu_admin_1 bash`
In the docker container:
```
cd /tmp
pip install idna\<2.6
```
Exit the docker container then:
`docker restart mailu_admin_1`

**Comment by kaiyou** [comment]
Thank you for providing the fix. I think we should wait for upstream to fix before we take any other action.

**Comment by kaiyou** [comment]
See #250 for long term plans regarding Certbot.

**Comment by kaiyou** [comment]
Certificate generation was rewritten and does not use certbot anymore.
