### ISSUE TITLE
Letsencrypt Certificate Renewal process gives 502 error

### ISSUE THREAD

**Issue by DenisBY** [Mailu/Mailu#2417]
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9 (last pulled - today)

## Description
```
# ./letsencrypt.py 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for example.com

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: example.com
  Type:   unauthorized
  Detail: x.x.x.x: Invalid response from http://example.com/.well-known/acme-challenge/tr6zr_eYXk0KFAM-FPG8cOoolwMZaDnEz7IQwT5eAIs: 502

Hint: The Certificate Authority couldn't exterally verify that the standalone plugin completed the required http-01 challenges. Ensure the plugin is configured correctly and that the changes it makes are accessible from the internet.

Some challenges have failed.
```
In `/etc/nginx/nginx.conf` in a container I found the following block:
```
    server {
      # Listen over HTTP
      listen 80;
      listen [::]:80;
      
      location ^~ /.well-known/acme-challenge/ {
          proxy_pass http://127.0.0.1:8008;
      
```
Also in the code https://github.com/Mailu/Mailu/blob/master/core/nginx/conf/nginx.conf#L63.
But nothing is listening on port 8008 in this container.

502 is definitely from a container as curl gives the same error during connecting to this container from a host machine:
```
# curl http://localhost:8080/.well-known/acme-challenge/
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

## Replication Steps
execute `./letsencrypt.py `

## Expected behaviour
The cert is renewed

**Comment by DenisBY** [comment]
It seems because of this:
```
{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/",
  "status": 429
}
2022-08-15 15:43:44,924:INFO:certbot.compat.misc:Running post-hook command: /config.py
2022-08-15 15:43:45,199:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.16.0', 'console_scripts', 'certbot')())
  File "/usr/lib/python3.9/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 1552, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 1414, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 117, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/renewal.py", line 333, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/client.py", line 375, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/client.py", line 407, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/usr/lib/python3.9/site-packages/acme/client.py", line 880, in new_order
    return cast(ClientV2, self.client).new_order(csr_pem)
  File "/usr/lib/python3.9/site-packages/acme/client.py", line 658, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/usr/lib/python3.9/site-packages/acme/client.py", line 86, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/acme/client.py", line 1198, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/acme/client.py", line 1211, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/usr/lib/python3.9/site-packages/acme/client.py", line 1068, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
2022-08-15 15:43:45,201:ERROR:certbot._internal.log:An unexpected error occurred:
2022-08-15 15:43:45,202:ERROR:certbot._internal.log:There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
```

**Comment by DenisBY** [comment]
It's not because of this, but because of:
```
2022-09-14 16:01:45,091:DEBUG:acme.standalone:Successfully bound to :8008 using IPv6
2022-09-14 16:01:45,092:DEBUG:acme.standalone:Certbot wasn't able to bind to :8008 using IPv4, this is often expected due to the dual stack nature of IPv6 socket implementations.
```
however 
```
      location ^~ /.well-known/acme-challenge/ {
          proxy_pass http://127.0.0.1:8008;
      }
```

nginx proxies to ipv4 but certbot listens only on ipv6. is there a workaround for this?

**Comment by DenisBY** [comment]
My fault. Wrong reverse proxy nginx configuration. I used `proxy_pass httpS://localhost:8080;` instead of `http`
