### ISSUE TITLE
socket.gaierror: [Errno -3] Try again

### ISSUE THREAD

**Issue by cloudwindy** [Mailu/Mailu#2481]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
$> docker ps -a | grep mailu
45d7ea2d2786   mailu/admin:1.9  "/bin/sh -c /start.py"   13 minutes ago   Up 13 minutes (unhealthy)
```

## Description
Admin does not start, causing all other containers unable to start.

## Replication Steps
1. Deploy docker-compose.yml produced by setup utility
2. Admin won't start

## Expected behaviour
Admin should start and be in a healthy status.

## Logs
After about 1 minute of no log, it raises the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/socrate/system.py", line 12, in resolve_hostname
    return socket.gethostbyname(hostname)
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1653, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1700, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 556, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 406, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 276, in locate_app
    return find_best_app(script_info, module)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 68, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 123, in call_factory
    return app_factory(*args, **kwargs)
  File "/app/mailu/__init__.py", line 81, in create_app
    return create_app_from_config(config)
  File "/app/mailu/__init__.py", line 21, in create_app_from_config
    config.init_app(app)
  File "/app/mailu/configuration.py", line 144, in init_app
    self.resolve_hosts()
  File "/app/mailu/configuration.py", line 116, in resolve_hosts
    self.config[f'{key}_ADDRESS'] = self.get_host_address(key)
  File "/app/mailu/configuration.py", line 112, in get_host_address
    return system.resolve_address(self.config[f'HOST_{name}'])
  File "/usr/lib/python3.9/site-packages/socrate/system.py", line 20, in resolve_address
    ip_address = resolve_hostname(hostname)
  File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f23e6b3b430 state=finished raised gaierror>]
```

**Comment by cloudwindy** [comment]
dup #1153
