### ISSUE TITLE
Cannot generate DKIM keys for long domain names

### ISSUE THREAD

**Issue by GodSaveTheDoge** [Mailu/Mailu#2687]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9` (just updated with `docker-compose pull`)

## Description
Mailu fails to generate DKIM keys for domains that are too long and, instead, fails with a 500 internal server error

## Replication Steps
- Go to the admin panel > mail domains
- Add `llllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.com`
- Try to generate new dkim keys

## Observed behaviour
It fails to generate them

## Expected behaviour
It should either generate them or tell the user that the domain name is too long (and maybe acknowledge it when the domain is added too)

## Logs
```
admin_1     | Traceback (most recent call last):
admin_1     |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
admin_1     |     response = self.full_dispatch_request()
admin_1     |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
admin_1     |     rv = self.handle_user_exception(e)
admin_1     |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
admin_1     |     rv = self.dispatch_request()
admin_1     |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
admin_1     |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
admin_1     |   File "/usr/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
admin_1     |     return func(*args, **kwargs)
admin_1     |   File "/app/mailu/ui/access.py", line 28, in wrapper
admin_1     |     return callback(function, args, kwargs, dargs, dkwargs)
admin_1     |   File "/app/mailu/ui/access.py", line 19, in callback
admin_1     |     return function(*args, **kwargs)
admin_1     |   File "/app/mailu/ui/access.py", line 105, in wrapper
admin_1     |     return function(*args, **kwargs)
admin_1     |   File "/app/mailu/ui/views/domains.py", line 77, in domain_genkeys
admin_1     |     models.db.session.commit()
admin_1     |   File "<string>", line 2, in commit
admin_1     |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
admin_1     |     self._transaction.commit(_to_root=self.future)
admin_1     |   File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 839, in commit
admin_1     |     self.session.dispatch.after_commit(self.session)
admin_1     |   File "/usr/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
admin_1     |     fn(*args, **kw)
admin_1     |   File "/app/mailu/models.py", line 176, in _save_dkim_keys
admin_1     |     obj.save_dkim_key()
admin_1     |   File "/app/mailu/models.py", line 207, in save_dkim_key
admin_1     |     with open(file_path, 'wb') as handle:
admin_1     | OSError: [Errno 36] Filename too long: '/dkim/llllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.com.dkim.key'
```

**Comment by elandorr** [comment]
For the record, this is an acceptable domain for e-mail according to this guy's dissection of the RFC: https://stackoverflow.com/questions/10552665/names-and-maximum-lengths-of-the-parts-of-a-url/66660651#66660651

>Max Length: 253 characters if you care about E-mail (max limit of the to field in SMTP is 255 characters, leaving you with a@(253-char-domain) as the longest possible domain in an email; 255 if you don't mind E-mail not working

You won't have a lot of inboxes available, though.

**Comment by elandorr** [comment]
This problem lies in the OS as the error suggests:

```
kdkimkllllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.com.dkim.key
```

Quoting https://serverfault.com/questions/9546/filename-length-limits-on-linux/9548#9548:

```
BTRFS   255 bytes
exFAT   255 UTF-16 characters
ext2    255 bytes
ext3    255 bytes
ext3cow 255 bytes
ext4    255 bytes
FAT32   8.3 (255 UCS-2 code units with VFAT LFNs)
NTFS    255 characters
XFS     255 bytes
```

Can't fix this, unless mailu changes the way it names the keys.

**Comment by GodSaveTheDoge** [comment]
> This problem lies in the OS as the error suggests:
> ...
> Can't fix this, unless mailu changes the way it names the keys.

That's exactly why I've opened this issue: to make you aware that not all valid domains are usable.
If you don't care enough to change the way mailu handles dkim keys feel free to close this issue, I don't either.

**Comment by GodSaveTheDoge** [comment]
>Do you have a domain like this?

Yes, I do. 

>As per that SO post, you'll be left with only 1 character at 253, or in your case 2 chars

Two chars: `l@`

**Comment by maximilize** [comment]
Confirmed and reproduced at HEAD. `save_dkim_key()` does `open(self._dkim_file(), 'wb')` (`models.py:216`); `_dkim_file()` builds the name from `DKIM_PATH = /dkim/{domain}.{selector}.key`. A domain name over `255 - len(".{selector}.key")` (246 bytes for the default selector) makes that single filename exceed 255 bytes, so `open()` raises `OSError [Errno 36] File name too long` in the `after_commit` listener `_save_dkim_keys` (`:175-179`) → unhandled 500. A valid 247-char domain (four ≤63 labels) triggers it; `DomainForm.name` has no length check, so it only fails later at genkeys.

Fix: reject names where `len(f"{name}.{DKIM_SELECTOR}.key") > 255` at creation with a user-facing error. I can PR that with a `tests/anonmail` regression test.

**Comment by nextgens** [comment]
The long term fix is to move the dkim keys in database so that we can tackle the other related DKIM tickets too: https://github.com/Mailu/Mailu/issues/2687 https://github.com/Mailu/Mailu/issues/2618 https://github.com/Mailu/Mailu/issues/2053 https://github.com/Mailu/Mailu/issues/2050 https://github.com/Mailu/Mailu/issues/1700 maybe even https://github.com/Mailu/Mailu/issues/1519

I was working on it at some point, here is how far I got:
https://github.com/Mailu/Mailu/files/12746951/0001-V1.txt

Feel free to take-over and send a PR for the long term fix
