### ISSUE TITLE
mailu admin not working with mysql in compose.yml

### ISSUE THREAD

**Issue by romannik007** [Mailu/Mailu#2713]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9.1`

## Description

```
docker compose ps
NAME                IMAGE                 COMMAND                  SERVICE             CREATED             STATUS                          PORTS
mailu-admin-1       mailu/admin:1.9.1     "/bin/sh -c /start.py"   admin               27 minutes ago      Up 26 minutes (unhealthy)       
mailu-antispam-1    mailu/rspamd:1.9      "/bin/sh -c /start.py"   antispam            35 minutes ago      Up 35 minutes (healthy)         11332/tcp, 11334-11335/tcp
mailu-antivirus-1   mailu/clamav:1.9      "/bin/sh -c /start.py"   antivirus           35 minutes ago      Restarting (0) 13 seconds ago   
mailu-fetchmail-1   mailu/fetchmail:1.9   "/fetchmail.py"          fetchmail           35 minutes ago      Up 35 minutes                   
mailu-front-1       mailu/nginx:1.9       "/bin/sh -c /start.py"   front               35 minutes ago      Up 35 minutes (healthy)         443/tcp, 10025/tcp, 10143/tcp, 0.0.0.0:10025->25/tcp, :::10025->25/tcp, 0.0.0.0:8080->80/tcp, :::8080->80/tcp, 0.0.0.0:10110->110/tcp, :::10110->110/tcp, 0.0.0.0:10143->143/tcp, :::10143->143/tcp, 0.0.0.0:10465->465/tcp, :::10465->465/tcp, 0.0.0.0:10587->587/tcp, :::10587->587/tcp, 0.0.0.0:10993->993/tcp, :::10993->993/tcp, 0.0.0.0:10995->995/tcp, :::10995->995/tcp
mailu-imap-1        mailu/dovecot:1.9     "/bin/sh -c /start.py"   imap                35 minutes ago      Up 35 minutes (healthy)         110/tcp, 143/tcp, 993/tcp, 2525/tcp, 4190/tcp
mailu-mysql-1       mysql:5.7             "sh -c 'export MYSQL…"   mysql               36 minutes ago      Up 36 minutes (healthy)         
mailu-redis-1       redis:alpine          "docker-entrypoint.s…"   redis               27 minutes ago      Up 26 minutes                   6379/tcp
mailu-resolver-1    mailu/unbound:1.9     "/bin/sh -c /start.py"   resolver            27 minutes ago      Up 26 minutes (healthy)         53/tcp, 53/udp
mailu-smtp-1        mailu/postfix:1.9     "/bin/sh -c /start.py"   smtp                35 minutes ago      Up 35 minutes (healthy)         25/tcp, 10025/tcp
mailu-webdav-1      mailu/radicale:1.9    "/bin/sh -c 'radical…"   webdav              35 minutes ago      Up 35 minutes (healthy)         5232/tcp
mailu-webmail-1     mailu/roundcube:1.9   "docker-php-entrypoi…"   webmail             35 minutes ago      Up 35 minutes (healthy)         80/tcp


```
`docker compose exec admin flask mailu admin admin domail.ru 123456`

<details>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3240, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host '@172.30.20.2' (-3)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/mailu/manage.py", line 63, in admin
    domain = models.Domain.query.get(domain_name)
  File "<string>", line 2, in get
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 943, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 947, in _get_impl
    return self.session._get_impl(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2869, in _get_impl
    return db_load_fn(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 524, in load_on_pk_identity
    session.execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3194, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3273, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2097, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3240, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host '@172.30.20.2' (-3)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
</details>

` docker compose exec admin ping 172.30.20.2`

```
PING 172.30.20.2 (172.30.20.2): 56 data bytes
64 bytes from 172.30.20.2: seq=0 ttl=64 time=0.122 ms
64 bytes from 172.30.20.2: seq=1 ttl=64 time=0.133 ms
64 bytes from 172.30.20.2: seq=2 ttl=64 time=0.130 ms
64 bytes from 172.30.20.2: seq=3 ttl=64 time=0.151 ms
64 bytes from 172.30.20.2: seq=4 ttl=64 time=0.226 ms
```

**`docker compose exec admin env | grep DB`**
```
ROUNDCUBE_DB_PW=A&5kV6VYt8HUtE@
ROUNDCUBE_DB_NAME=roundcube
DB_PW=A&5kV6VYt8HUtE@
DB_HOST=172.30.20.2
DB_FLAVOR=mysql
DB_USER=admin
ROUNDCUBE_DB_FLAVOR=mysql
ROUNDCUBE_DB_USER=roundcube
DB_NAME=admin
ROUNDCUBE_DB_HOST=mysql

```

**Comment by Diman0** [comment]
The issues section is not for user support. You can get user support on the matrix channel. 
SQLAlchemy states that the database server cannot be found 172.30.20.2. Either you specified an incorrect IP address or the myself container is not reachable.
