### ISSUE TITLE
config-import failes with error '[TypeError] encoding without a string argument'

### ISSUE THREAD

**Issue by 4athan** [Mailu/Mailu#2747]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master and 2.0`

## Description
An exported config yaml or JSON with secrets can not be imported on another similar system. Every try produces: 
...
Error: [TypeError] encoding without a string argument
...

## Replication Steps
Export a config file on the cli with config-export and --secrets option. Then try to import it back in.

## Observed behaviour
...
Error: [TypeError] encoding without a string argument
...

## Expected behaviour
Config is imported.

## Logs

I have not seen any output related to this in the logs.

**Comment by Diman0** [comment]
I can replicate this using:
```
docker compose exec -T admin flask mailu config-export --secrets > test.yml
docker compose exec -T admin flask mailu config-import -nv < test.yml
Error: [TypeError] encoding without a string argument
```

But it also occurs when secrets are not included:
```
docker compose exec -T admin flask mailu config-export > test2.yml
docker compose exec -T admin flask mailu config-import -nv < test2.yml
Error: [TypeError] encoding without a string argument
```

This appears to be a defect.

**Comment by Diman0** [comment]
@4athan Please run the same import command again with the `--debug` switch and add the output to this issue.  I want ot make sure you have the same stack trace.

```
docker compose exec -T admin flask mailu config-import --debug --verbose --dry-run /data/test2.yml
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:DELETE FROM alias
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] ()
INFO:sqlalchemy.engine.Engine:DELETE FROM domain
INFO:sqlalchemy.engine.Engine:[generated in 0.00023s] ()
INFO:sqlalchemy.engine.Engine:DELETE FROM relay
INFO:sqlalchemy.engine.Engine:[generated in 0.00014s] ()
INFO:sqlalchemy.engine.Engine:DELETE FROM user
INFO:sqlalchemy.engine.Engine:[generated in 0.00015s] ()
INFO:sqlalchemy.engine.Engine:ROLLBACK
Traceback (most recent call last):
  File "/app/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.10/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/mailu/manage.py", line 344, in config_import
    config = schema.loads(source)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 756, in loads
    return self.load(data, many=many, partial=partial, unknown=unknown)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 500, in _call_and_store
    value = getter_func(data)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/fields.py", line 370, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/fields.py", line 673, in _deserialize
    return self._load(value, data, partial=partial)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/fields.py", line 656, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
  File "/app/venv/lib/python3.10/site-packages/marshmallow_sqlalchemy/load_instance_mixin.py", line 96, in load
    return super().load(data, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 618, in _deserialize
    ret_l = [
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 621, in <listcomp>
    self._deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 500, in _call_and_store
    value = getter_func(data)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/fields.py", line 370, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/app/mailu/schemas.py", line 613, in _deserialize
    serialization.load_pem_private_key(bytes(value, "ascii"), password=None)
TypeError: encoding without a string argument
```

**Comment by 4athan** [comment]
Hello @Diman0 ,

Here is the debug stack trace:

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT domain.created_at AS domain_created_at, domain.updated_at AS domain_updated_at, domain.comment AS domain_comment, domain.name AS domain_name, domain.max_users AS domain_max_users, domain.max_aliases AS domain_max_aliases, domain.max_quota_bytes AS domain_max_quota_bytes, domain.signup_enabled AS domain_signup_enabled
FROM domain
WHERE domain.name = ?
 LIMIT ? OFFSET ?
INFO:sqlalchemy.engine.Engine:[generated in 0.00045s] ('jgeg.de', 1, 0)
INFO:sqlalchemy.engine.Engine:SELECT domain.created_at AS domain_created_at, domain.updated_at AS domain_updated_at, domain.comment AS domain_comment, domain.name AS domain_name, domain.max_users AS domain_max_users, domain.max_aliases AS domain_max_aliases, domain.max_quota_bytes AS domain_max_quota_bytes, domain.signup_enabled AS domain_signup_enabled
FROM domain
WHERE domain.name = ?
 LIMIT ? OFFSET ?
INFO:sqlalchemy.engine.Engine:[cached since 0.002913s ago] ('meshigene.de', 1, 0)
INFO:sqlalchemy.engine.Engine:SELECT domain.created_at AS domain_created_at, domain.updated_at AS domain_updated_at, domain.comment AS domain_comment, domain.name AS domain_name, domain.max_users AS domain_max_users, domain.max_aliases AS domain_max_aliases, domain.max_quota_bytes AS domain_max_quota_bytes, domain.signup_enabled AS domain_signup_enabled
FROM domain
WHERE domain.name = ?
 LIMIT ? OFFSET ?
INFO:sqlalchemy.engine.Engine:[cached since 0.004321s ago] ('lemnea.com', 1, 0)
INFO:sqlalchemy.engine.Engine:ROLLBACK
Traceback (most recent call last):
  File "/app/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.10/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/mailu/manage.py", line 344, in config_import
    config = schema.loads(source)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 756, in loads
    return self.load(data, many=many, partial=partial, unknown=unknown)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 500, in _call_and_store
    value = getter_func(data)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/fields.py", line 370, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/fields.py", line 673, in _deserialize
    return self._load(value, data, partial=partial)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/fields.py", line 656, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
  File "/app/venv/lib/python3.10/site-packages/marshmallow_sqlalchemy/load_instance_mixin.py", line 96, in load
    return super().load(data, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 618, in _deserialize
    ret_l = [
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 621, in <listcomp>
    self._deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 664, in _deserialize
    value = self._call_and_store(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 500, in _call_and_store
    value = getter_func(data)
  File "/app/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 661, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/app/venv/lib/python3.10/site-packages/marshmallow/fields.py", line 370, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/app/mailu/schemas.py", line 613, in _deserialize
    serialization.load_pem_private_key(bytes(value, "ascii"), password=None)
TypeError: encoding without a string argument

**Comment by Diman0** [comment]
@4athan 
It looks like the bug is caused by the dkim de-serialization functionality. As a workaround it should work when you remove all dkim_key elements from your config yaml.

You can manually migrate the dkim keys by copying /mailu/dkim from the old server to the new server.

I think I found a fix. I expect a fix to be released within a week.

**Comment by 4athan** [comment]
@Diman0 ,
Thank you for the info how to manually migrate the keys and the fix the future. I overlooked this possibility until now.
