### ISSUE TITLE
error on unbound on 2.0.5: could not open autotrust file for writing

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#2775]
### Environment

- [X] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0.5`

## Description
When starting unbound in version 2.0.5 on my raspberrypi 4 (arm64), I get the following error and the container exits:
```
2023-04-16T17:58:37.281757085Z [1681667917] unbound[1:0] notice: init module 0: validator

2023-04-16T17:58:37.282211468Z [1681667917] unbound[1:0] notice: init module 1: iterator

2023-04-16T17:58:37.442919841Z [1681667917] unbound[1:0] info: start of service (unbound 1.17.1).

2023-04-16T17:58:37.477399375Z [1681667917] unbound[1:0] info: generate keytag query _ta-4f66. NULL IN

2023-04-16T17:58:37.477490355Z [1681667917] unbound[1:0] fatal error: could not open autotrust file for writing, trusted-key.key.1-0-7fbbaf1510: Permission denied
```
As far as I can see, I just changed from 2.0.4 to 2.0.5

**Comment by leolivier** [comment]
I also have errors in admin for 2.0.5:
```
2023-04-16T17:59:16.023922000Z Fatal Python error: init_import_site: Failed to import the site module

2023-04-16T17:59:16.025068000Z Python runtime state: initialized

2023-04-16T17:59:16.026782000Z Traceback (most recent call last):

2023-04-16T17:59:16.027150000Z   File "/usr/lib/python3.10/site.py", line 617, in <module>

2023-04-16T17:59:16.027323000Z     main()

2023-04-16T17:59:16.027454000Z   File "/usr/lib/python3.10/site.py", line 600, in main

2023-04-16T17:59:16.032607000Z     known_paths = venv(known_paths)

2023-04-16T17:59:16.033138000Z   File "/usr/lib/python3.10/site.py", line 518, in venv

2023-04-16T17:59:16.034178000Z     with open(virtual_conf, encoding='utf-8') as f:

2023-04-16T17:59:16.034632000Z PermissionError: [Errno 13] Permission denied: '/app/venv/pyvenv.cfg'
```

I'm currently switching back to 2.0.4 to see if it solves the issue or not

**Comment by leolivier** [comment]
Looks like it's not linked to a version of mailu :/ 
I tried them all back to 2.0.1 and same error

**Comment by leolivier** [comment]
Hi, I reopen this issue as I cannot understand where it comes from.
I have the issue with all versions of resolver from 2.0.1 since ~10 days, this totally prevents my mailu server to work. It used to work very well previously and I cannot see what has changed since then.
I found the following issue that really looks like this one here: https://github.com/NLnetLabs/unbound/issues/447 but the solution is to change the permission on files which I can't do here as the files are inside the container and I can't start the container.
The error with latest resolver version is: (hardened malloc thing added but not linked I think)
```
2023-04-22T08:44:53.492879942Z WARNING:root:Disabling hardened-malloc on this CPU

2023-04-22T08:44:55.505512767Z [1682153095] unbound[1:0] notice: init module 0: validator

2023-04-22T08:44:55.506421681Z [1682153095] unbound[1:0] notice: init module 1: iterator

2023-04-22T08:44:55.680296747Z [1682153095] unbound[1:0] info: start of service (unbound 1.17.1).

2023-04-22T08:44:55.702092086Z [1682153095] unbound[1:0] info: generate keytag query _ta-4f66. NULL IN

2023-04-22T08:44:55.840247056Z [1682153095] unbound[1:0] fatal error: could not open autotrust file for writing, trusted-key.key.1-0-7f9d343510: Permission denied
```
Also, I tried to look at the permissions in the image with docker run -it and got:
```
/app# more /start.py
#!/usr/bin/env python3

import os
import logging as log
import sys
from socrate import conf, system

system.set_env()

conf.jinja("/unbound.conf", os.environ, "/etc/unbound/unbound.conf")

os.execv("/usr/sbin/unbound", ["unbound", "-c", "/etc/unbound/unbound.conf"])

/app# grep -v '^\s*#\|^\s*$' /etc/unbound/unbound.conf
server:
        trust-anchor-file: "/usr/share/dnssec-root/trusted-key.key"
python:
dynlib:
remote-control:
        control-enable: yes
        control-interface: /run/unbound.control.sock
/app# ls -al /usr/share/dnssec-root/
total 12
drwxr-xr-x    2 root     root          4096 Apr 20 17:03 .
drwxr-xr-x    1 root     root          4096 Apr 20 17:03 ..
-rw-r--r--    1 root     root           369 Aug  6  2022 trusted-key.key
```
As the error is ` fatal error: could not open autotrust file for writing, trusted-key.key.1-0-7f9d343510: Permission denied` it's a relative path and I don't really know which directory the file is.
Also, I don't know which user is executing the container. If it's not root and if the file is to be created in /usr/share/dnssec-root/ then I get the error but 
1. I don't know how to check this
2. I don't understand why it used to work
3. I don't know how to fix (except by creating a new container based on the original image and with some changes in the permissions)

Any help appreciated

**Comment by leolivier** [comment]
As the start.py script starts with `conf.jinja("/unbound.conf", os.environ, "/etc/unbound/unbound.conf")`, it's very probable that if I look in the image and not in the started container, I should look at /unbound.conf and not at /etc/unbound/unbound.conf.
So /unbound.conf contains:
```
server:
  verbosity: 1
  interface: 0.0.0.0
{{- '  interface: ::0' if SUBNET6 }}
  logfile: ""
  do-ip4: yes
  do-ip6: {{ 'yes' if SUBNET6 else 'no' }}
  do-udp: yes
  do-tcp: yes
  do-daemonize: no
  access-control: {{ SUBNET }} allow
{%- if SUBNET6 %}
  access-control: {{ SUBNET6 }} allow
{%- endif %}
  directory: "/etc/unbound"
  username: unbound
  auto-trust-anchor-file: trusted-key.key
  root-hints: "/etc/unbound/root.hints"
  hide-identity: yes
  hide-version: yes
  cache-min-ttl: 300
```
with no ref to /usr/share/dnssec-root/  but a ref to 
```
  directory: "/etc/unbound"
  username: unbound
  auto-trust-anchor-file: trusted-key.key
```
So looking at /etc/unbound, I can see:
```
/app# ls -al /etc/unbound/
total 72
drwxrwxr-x    2 root     unbound       4096 Apr 20 17:03 .
drwxr-xr-x    1 root     root          4096 Apr 22 10:26 ..
-rw-r--r--    1 root     root          3311 Apr 20 17:03 root.hints
-rw-r--r--    1 root     root           758 Apr 20 17:03 trusted-key.key
-rw-r--r--    1 root     root         50802 Jan 21 13:54 unbound.conf
```
and again, the directory is not belonging to unbound (but it is writable by group unbound so might be enough) and the trusted-key.key is not writable by unbound at all...

**Comment by leolivier** [comment]
This is a pure docker issue I think
I fixed this one by mounting the /etc/unbound directory on a user volume where I copied exactly the same files with the same content and permissions as in the image and it started to work (and the trusted-key.key file was chown'd to unbound:unbound).
So something related to the docker repo and overlay2, I suppose but hard to understand.
Now, I have the same kind of issues on smtp, on admin, ... so I don't know what to do. 😞 
eg in the admin image, I get
```
2023-04-22T13:29:20.242781000Z Fatal Python error: init_import_site: Failed to import the site module

2023-04-22T13:29:20.243226000Z Python runtime state: initialized

2023-04-22T13:29:20.243464000Z Traceback (most recent call last):

2023-04-22T13:29:20.243821000Z   File "/usr/lib/python3.10/site.py", line 617, in <module>

2023-04-22T13:29:20.245603000Z     main()

2023-04-22T13:29:20.245950000Z   File "/usr/lib/python3.10/site.py", line 600, in main

2023-04-22T13:29:20.247601000Z     known_paths = venv(known_paths)

2023-04-22T13:29:20.247921000Z   File "/usr/lib/python3.10/site.py", line 518, in venv

2023-04-22T13:29:20.249432000Z     with open(virtual_conf, encoding='utf-8') as f:

2023-04-22T13:29:20.249746000Z PermissionError: [Errno 13] Permission denied: '/app/venv/pyvenv.cfg'

2023-04-22T13:29:20.252961000Z Traceback (most recent call last):

2023-04-22T13:29:20.253352000Z   File "/start.py", line 52, in <module>

2023-04-22T13:29:20.253990000Z     test_DNS()

2023-04-22T13:29:20.254258000Z   File "/start.py", line 27, in test_DNS

2023-04-22T13:29:20.254965000Z     import dns.resolver

2023-04-22T13:29:20.255271000Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

2023-04-22T13:29:20.255862000Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

2023-04-22T13:29:20.256513000Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

2023-04-22T13:29:20.256971000Z   File "<frozen importlib._bootstrap_external>", line 879, in exec_module

2023-04-22T13:29:20.257604000Z   File "<frozen importlib._bootstrap_external>", line 1016, in get_code

2023-04-22T13:29:20.258031000Z   File "<frozen importlib._bootstrap_external>", line 1073, in get_data

2023-04-22T13:29:20.258571000Z PermissionError: [Errno 13] Permission denied: '/app/venv/lib/python3.10/site-packages/dns/__init__.py'
```
and if I run the image like this: 
```
/docker/mailu $ docker run -it -u 100 245584de6e79 bash
32172d5ae490:~$ id
uid=100(mailu) gid=1000(mailu) groups=1000(mailu)
32172d5ae490:~$  ls -al /app/venv/
ls: can't open '/app/venv/': Permission denied
total 0
32172d5ae490:~$ ls -al /app/
total 20
drwxr-sr-x    1 mailu    mailu         4096 Apr 20 17:05 .
drwxr-xr-x    1 root     root          4096 Apr 22 13:10 ..
drwxr-sr-x    1 root     mailu         4096 Apr 20 10:33 mailu
drwxr-sr-x    3 root     mailu         4096 Mar 23 12:14 migrations
drwxr-sr-x    1 root     mailu         4096 Apr 20 16:31 venv
32172d5ae490:~$ cd /app/
32172d5ae490:~$ cd venv/
32172d5ae490:~/venv$ ls
ls: can't open '.': Permission denied
```

**Comment by leolivier** [comment]
I ended up in stopping and removing all the containers, then removing all the images, then `docker system prune -f` and restart from scratch and it now works
