### ISSUE TITLE
No special characters in passwords allowed

### ISSUE THREAD

**Issue by powerpaul17** [Mailu/Mailu#2837]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

Authentication fails when using special characters in a user's password.

I cannot use special characters in a password, e.g. '€'. It worked in version 1.9

## Replication Steps

Use for example '€' in a user's password.

## Observed behaviour

Clients are not able to login to IMAP server.

## Expected behaviour

Clients should be able to login to IMAP server.

## Logs

Logs from `admin` container:

```
192.168.203.1 - - [30/May/2023:08:39:07 +0000] "GET /internal/auth/email HTTP/1.0" 500 0 "-" "-"
[2023-05-30 08:39:07 +0000] [18] [ERROR] Error handling request /internal/auth/email
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/app/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 331, in handle_request
    resp.close()
  File "/app/venv/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 391, in close
    self.send_headers()
  File "/app/venv/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 322, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "latin-1"))
  File "/app/venv/lib/python3.10/site-packages/gunicorn/util.py", line 565, in to_bytestring
    return value.encode(encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u20ac' in position 267: ordinal not in range(256)
```

**Comment by Diman0** [comment]
I can only replicate this for imap/smtp login (so login for email clients).
Login via the SSO form (Web) works fine.

**Comment by powerpaul17** [comment]
Thanks for the very quick fix.. :relaxed:
