### ISSUE TITLE
Unable to use wildcard (*.parentdomain) for Relayed domains

### ISSUE THREAD

**Issue by Iridescens** [Mailu/Mailu#2845]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

Client: Docker Engine - Community
 Version:           20.10.14

### Version

- Version: `2.0`

## Description

We have a BIG list of to-be-relayed domains for our branch offices in parent organization.
When trying to use same wildcard syntax (*.parentdomain) as in MS Exchange for Relayed domains the WebAdmin gives error page
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

## Replication Steps

Relayed domains -> New relayed domain -> Enter `*.domain` in "Relayed domain name", press Save, Get error page.

## Observed behaviour

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

## Expected behaviour

Saved wildcard relayed domains.
Mailu properly processing every and each matched subdomain of wildcard, like dom1.parentdomain, dom2.parentdomain.

## Logs

```python
[2023-06-02 13:51:33,942] ERROR in app: Exception on /admin/relay/create [POST]
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context
    context = constructor(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1660, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 46, in process_bind_param
    return idna.encode(value.lower()).decode('ascii')
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 360, in encode
    s = alabel(label)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 258, in alabel
    ulabel(label_bytes)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 297, in ulabel
    check_label(label_bytes)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 250, in check_label
    raise InvalidCodepoint('Codepoint {} at position {} of {} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+002A at position 1 of '*' not allowed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/venv/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/mailu/ui/access.py", line 36, in wrapper
    return callback(function, args, kwargs, (), {})
  File "/app/mailu/ui/access.py", line 19, in callback
    return function(*args, **kwargs)
  File "/app/mailu/ui/views/relays.py", line 20, in relay_create
    conflicting_domain = models.Domain.query.get(form.name.data)
  File "<string>", line 2, in get
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 947, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 951, in _get_impl
    return self.session._get_impl(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2955, in _get_impl
    return db_load_fn(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1806, in _execute_context
    self._handle_dbapi_exception(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context
    context = constructor(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1660, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 46, in process_bind_param
    return idna.encode(value.lower()).decode('ascii')
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 360, in encode
    s = alabel(label)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 258, in alabel
    ulabel(label_bytes)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 297, in ulabel
    check_label(label_bytes)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 250, in check_label
    raise InvalidCodepoint('Codepoint {} at position {} of {} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
sqlalchemy.exc.StatementError: (idna.core.InvalidCodepoint) Codepoint U+002A at position 1 of '*' not allowed
[SQL: SELECT domain.created_at AS domain_created_at, domain.updated_at AS domain_updated_at, domain.comment AS domain_comment, domain.name AS domain_name, domain.max_users AS domain_max_users, domain.max_aliases AS domain_max_aliases, domain.max_quota_bytes AS domain_max_quota_bytes, domain.signup_enabled AS domain_signup_enabled
FROM domain
WHERE domain.name = ?]
[parameters: [{'pk_1': '*.parentdomain'}]]
```

**Comment by nextgens** [comment]
What if you put ``.parentdomain`` instead? IIRC the wildcard is implied when there is a leading dot

**Comment by Iridescens** [comment]
Still error, but logs are slightly different:
```python
[2023-06-02 14:09:37,657] ERROR in app: Exception on /admin/relay/create [POST]
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context
    context = constructor(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1660, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 46, in process_bind_param
    return idna.encode(value.lower()).decode('ascii')
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 360, in encode
    s = alabel(label)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 258, in alabel
    ulabel(label_bytes)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 297, in ulabel
    check_label(label_bytes)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 228, in check_label
    raise IDNAError('Empty Label')
idna.core.IDNAError: Empty Label

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/venv/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/mailu/ui/access.py", line 36, in wrapper
    return callback(function, args, kwargs, (), {})
  File "/app/mailu/ui/access.py", line 19, in callback
    return function(*args, **kwargs)
  File "/app/mailu/ui/views/relays.py", line 20, in relay_create
    conflicting_domain = models.Domain.query.get(form.name.data)
  File "<string>", line 2, in get
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 947, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 951, in _get_impl
    return self.session._get_impl(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2955, in _get_impl
    return db_load_fn(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1806, in _execute_context
    self._handle_dbapi_exception(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1800, in _execute_context
    context = constructor(
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/app/venv/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1660, in process
    return process_param(value, dialect)
  File "/app/mailu/models.py", line 46, in process_bind_param
    return idna.encode(value.lower()).decode('ascii')
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 360, in encode
    s = alabel(label)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 258, in alabel
    ulabel(label_bytes)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 297, in ulabel
    check_label(label_bytes)
  File "/app/venv/lib/python3.10/site-packages/idna/core.py", line 228, in check_label
    raise IDNAError('Empty Label')
sqlalchemy.exc.StatementError: (idna.core.IDNAError) Empty Label
[SQL: SELECT domain.created_at AS domain_created_at, domain.updated_at AS domain_updated_at, domain.comment AS domain_comment, domain.name AS domain_name, domain.max_users AS domain_max_users, domain.max_aliases AS domain_max_aliases, domain.max_quota_bytes AS domain_max_quota_bytes, domain.signup_enabled AS domain_signup_enabled
FROM domain
WHERE domain.name = ?]
[parameters: [{'pk_1': '.parentdomain'}]]
```

**Comment by Diman0** [comment]
This functionality was not created to work with wildcards. I will mark this as an enhancement request.

For adding many items, you could consider using the RESTful API (https://mailu.io/2.0/api.html) or the CLI import https://mailu.io/2.0/cli.html#config-import.

**Comment by Iridescens** [comment]
Perhaps this link might be helpful for whoever may attempt to implement this enhancement: https://github.com/pypa/pipenv/blob/3226a9fd013ddfa4ac91c35eac3211846006d1c5/pipenv/patched/pip/_vendor/urllib3/contrib/pyopenssl.py#L194

> For adding many items, you could consider using the RESTful API (https://mailu.io/2.0/api.html) or the CLI import https://mailu.io/2.0/cli.html#config-import.

Thank you for suggesting `config-import` CLI functionality, I found it very useful for workaround.
