### ISSUE TITLE
ERROR: manifest for mailu/radicale:master not found

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#285]
Getting this since you merged refactor-nginx to master

**Comment by kaiyou** [comment]
Could you specify the context, when do you get the error exactly?

**Comment by SaiGonSeamus** [comment]
Pulling down master, get an error when the value is either radicale or none

```
root@mail:/mailu# docker-compose pull
Pulling webdav (mailu/none:master)...
ERROR: manifest for mailu/none:master not found
```

**Comment by kaiyou** [comment]
Oh, then my bad: simply the `master` branch is mapped to the `latest` tag on Docker, not `master` :)

**Comment by SaiGonSeamus** [comment]
I can get it to come up with latest but there are a mass of imap and smtp errors in the logs and I can't access the GUIs.

**Comment by kaiyou** [comment]
Could you be more specific about imap and smtp errors? maybe provide some examples. We usually test what we write and push, even on `master`, so anything failing is not failing in our testing environment.

**Comment by SaiGonSeamus** [comment]
Here are a few examples

```
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
smtp_1       |     return self.environment.handle_exception(exc_info, True)
imap_1       |     return self.environment.handle_exception(exc_info, True)
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
antispam_1   | 2017-10-25 14:56:08 #9(normal) <o6xehe>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/2tld.inc.local
imap_1       |     reraise(exc_type, exc_value, tb)
imap_1       |   File "<template>", line 7, in top-level template code
smtp_1       |     reraise(exc_type, exc_value, tb)
smtp_1       |   File "<template>", line 7, in top-level template code
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
smtp_1       |     return getattr(obj, attribute)
antispam_1   | 2017-10-25 14:56:08 #9(normal) <o6xehe>; map; read_map_file: /var/lib/rspamd/2tld.inc.local: map file is unavailable for reading
imap_1       |     return getattr(obj, attribute)
smtp_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
smtp_1       | Traceback (most recent call last):
imap_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
imap_1       | Traceback (most recent call last):
antispam_1   | 2017-10-25 14:56:08 #9(normal) <mb4rmx>; map; rspamd_map_file_check_callback: old mtime is -1, new mtime is 1505042849 for map file /etc/rspamd/spf_dkim_whitelist.inc
antispam_1   | 2017-10-25 14:56:08 #9(normal) <mb4rmx>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/spf_dkim_whitelist.inc
imap_1       |   File "/start.py", line 14, in <module>
imap_1       |     convert(dovecot_file, os.path.join("/etc/dovecot", os.path.basename(dovecot_file)))
smtp_1       |   File "/start.py", line 15, in <module>
antispam_1   | 2017-10-25 14:56:08 #9(normal) <mb4rmx>; map; read_map_file: /etc/rspamd/spf_dkim_whitelist.inc: read map dat, 2605 bytes
imap_1       |   File "/start.py", line 8, in <lambda>
smtp_1       |     convert(postfix_file, os.path.join("/etc/postfix", os.path.basename(postfix_file)))
imap_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
smtp_1       |   File "/start.py", line 9, in <lambda>
smtp_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
smtp_1       |     return self.environment.handle_exception(exc_info, True)
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
imap_1       |     return self.environment.handle_exception(exc_info, True)
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
imap_1       |     reraise(exc_type, exc_value, tb)
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
smtp_1       |     reraise(exc_type, exc_value, tb)
smtp_1       |   File "<template>", line 7, in top-level template code
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
imap_1       |   File "<template>", line 7, in top-level template code
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
smtp_1       |     return getattr(obj, attribute)
antispam_1   | 2017-10-25 14:56:08 #9(normal) <mb4rmx>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/spf_dkim_whitelist.inc.local
smtp_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
smtp_1       | Traceback (most recent call last):
smtp_1       |   File "/start.py", line 15, in <module>
smtp_1       |     convert(postfix_file, os.path.join("/etc/postfix", os.path.basename(postfix_file)))
smtp_1       |   File "/start.py", line 9, in <lambda>
smtp_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
imap_1       |     return getattr(obj, attribute)
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
smtp_1       |     return self.environment.handle_exception(exc_info, True)
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
smtp_1       |     reraise(exc_type, exc_value, tb)
smtp_1       |   File "<template>", line 7, in top-level template code
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
smtp_1       |     return getattr(obj, attribute)
smtp_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
smtp_1       | Traceback (most recent call last):
smtp_1       |   File "/start.py", line 15, in <module>
smtp_1       |     convert(postfix_file, os.path.join("/etc/postfix", os.path.basename(postfix_file)))
smtp_1       |   File "/start.py", line 9, in <lambda>
smtp_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
smtp_1       |     return self.environment.handle_exception(exc_info, True)
imap_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
imap_1       | Traceback (most recent call last):
imap_1       |   File "/start.py", line 14, in <module>
imap_1       |     convert(dovecot_file, os.path.join("/etc/dovecot", os.path.basename(dovecot_file)))
imap_1       |   File "/start.py", line 8, in <lambda>
imap_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
imap_1       |     return self.environment.handle_exception(exc_info, True)
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
imap_1       |     reraise(exc_type, exc_value, tb)
imap_1       |   File "<template>", line 7, in top-level template code
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
imap_1       |     return getattr(obj, attribute)
imap_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
imap_1       | Traceback (most recent call last):
imap_1       |   File "/start.py", line 14, in <module>
imap_1       |     convert(dovecot_file, os.path.join("/etc/dovecot", os.path.basename(dovecot_file)))
imap_1       |   File "/start.py", line 8, in <lambda>
antispam_1   | 2017-10-25 14:56:08 #9(normal) <mb4rmx>; map; read_map_file: /var/lib/rspamd/spf_dkim_whitelist.inc.local: map file is unavailable for reading
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
smtp_1       |     reraise(exc_type, exc_value, tb)
smtp_1       |   File "<template>", line 7, in top-level template code
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
smtp_1       |     return getattr(obj, attribute)
smtp_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
smtp_1       | Traceback (most recent call last):
smtp_1       |   File "/start.py", line 15, in <module>
smtp_1       |     convert(postfix_file, os.path.join("/etc/postfix", os.path.basename(postfix_file)))
smtp_1       |   File "/start.py", line 9, in <lambda>
smtp_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
smtp_1       |     return self.environment.handle_exception(exc_info, True)
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
smtp_1       |     reraise(exc_type, exc_value, tb)
smtp_1       |   File "<template>", line 7, in top-level template code
```
```
imap_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
imap_1       |     return self.environment.handle_exception(exc_info, True)
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
imap_1       |     reraise(exc_type, exc_value, tb)
imap_1       |   File "<template>", line 7, in top-level template code
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
imap_1       |     return getattr(obj, attribute)
imap_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
imap_1       | Traceback (most recent call last):
imap_1       |   File "/start.py", line 14, in <module>
imap_1       |     convert(dovecot_file, os.path.join("/etc/dovecot", os.path.basename(dovecot_file)))
imap_1       |   File "/start.py", line 8, in <lambda>
imap_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
imap_1       |     return self.environment.handle_exception(exc_info, True)
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
imap_1       |     reraise(exc_type, exc_value, tb)
imap_1       |   File "<template>", line 7, in top-level template code
imap_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
imap_1       |     return getattr(obj, attribute)
imap_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
smtp_1       |     return getattr(obj, attribute)
smtp_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
smtp_1       | Traceback (most recent call last):
smtp_1       |   File "/start.py", line 15, in <module>
smtp_1       |     convert(postfix_file, os.path.join("/etc/postfix", os.path.basename(postfix_file)))
smtp_1       |   File "/start.py", line 9, in <lambda>
smtp_1       |     convert = lambda src, dst: open(dst, "w").write(jinja2.Template(open(src).read()).render(**os.environ))
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
smtp_1       |     return self.environment.handle_exception(exc_info, True)
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
smtp_1       |     reraise(exc_type, exc_value, tb)
smtp_1       |   File "<template>", line 7, in top-level template code
smtp_1       |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
smtp_1       |     return getattr(obj, attribute)
smtp_1       | jinja2.exceptions.UndefinedError: 'HOSTNAMES' is undefined
```

**Comment by kaiyou** [comment]
Hm, did you update to `master` without updating your `.env` and `docker-compose.yml`?
There are tons of changes in these files and you should get fresh ones and insert your settings in there. This is why running `master` on production is definitely not recommended, changes happen to configuration files and data structures that you must keep up with if you want your setup to run fine :)

**Comment by SaiGonSeamus** [comment]
No. This is a completely fresh install. Using the new env and yml with the new IPv6 settings. Pulling from latest.

**Comment by kaiyou** [comment]
It seems that `HOSTNAMES` is not defined. Is it defined in your `.env` ? Be careful, it was renamed from `HOSTNAME` to `HOSTNAMES` because it now supports multiple hostnames.

**Comment by SaiGonSeamus** [comment]
Ah, that's it I think. Cheers for this. It's late now. I'll run a fresh install in the morning.

**Comment by SaiGonSeamus** [comment]
Working perfectly now. Thank you. A+ on ssllabs with a Comodo cert.
