### ISSUE TITLE
Domain POST and PATCH API not working

### ISSUE THREAD

**Issue by mchlrv** [Mailu/Mailu#3001]
## Environment & Version

- Docker Compose version v2.21.0
- MAILU Version 2.0

## Description
When using the API to either create (POST) or update (PATCH) a domain it states the the domain has been created/updated, but not all settings are respected such as:
- comment
- max_users
- max_aliases
- max_quota_bytes

## Replication Steps
Use postman to send a API call with below JSON body. This will result in no updates except for comment to be '0'.
```
{
    "comment": "Test2",
    "max_users": 6,
    "max_aliases": -1,
    "max_quota_bytes": 6000000000,
    "signup_enabled": false,
    "alternatives": []
}
```

## Observed behaviour
```
{
    "code": 200,
    "message": "Domain example.org has been updated"
}
```
But all mentioned field are still at the current (old) value.

## Expected behaviour
Values to be updated as configured in the API call.

## Logs
No logs are show during the execution other then a connection. However during one of the test below was show in the output.
```
/app/mailu/api/common.py:15: SAWarning: SELECT statement has a cartesian product between FROM element(s) "domain" and FROM element "anon_2".  Apply join condition(s) between each element to resolve.
mailu-admin-1  |   if models.db.session.query(u.exists()).scalar():
mailu-admin-1  | [2023-10-24 14:34:27,712] ERROR in app: Exception on /api/v1/domain/example.org [PATCH]
mailu-admin-1  | Traceback (most recent call last):
mailu-admin-1  |   File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
mailu-admin-1  |     rv = self.dispatch_request()
mailu-admin-1  |   File "/app/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
mailu-admin-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
mailu-admin-1  |   File "/app/venv/lib/python3.10/site-packages/flask_restx/api.py", line 404, in wrapper
mailu-admin-1  |     resp = resource(*args, **kwargs)
mailu-admin-1  |   File "/app/venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
mailu-admin-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
mailu-admin-1  |   File "/app/venv/lib/python3.10/site-packages/flask_restx/resource.py", line 46, in dispatch_request
mailu-admin-1  |     resp = meth(*args, **kwargs)
mailu-admin-1  |   File "/app/mailu/api/common.py", line 41, in decorated_function
mailu-admin-1  |     return func(*args, **kwds)
mailu-admin-1  |   File "/app/mailu/api/v1/domains.py", line 174, in patch
mailu-admin-1  |     alternative = models.Alternative(name=item, domain_name=data['name'])
mailu-admin-1  | KeyError: 'name'
```

**Comment by Diman0** [comment]
Thank you for reporting this bug. This has been fixed on master. This will be included in the next major Mailu release. 
To see this for yourself you can check out the [demo server](https://mailu.io/2.0/demo.html). The demo server runs the master branch.
