### ISSUE TITLE
Announces fail

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#309]
Currently the admin container sends announces directly to Postfix, which might not be the best way to go.

Error message:
```
Chrome/62.0.3202.75 Safari/537.36"
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 36, in wrapper
admin_1      |     return callback(function, args, kwargs, (), {})
admin_1      |   File "/app/mailu/ui/access.py", line 19, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/views/base.py", line 63, in announcement
admin_1      |     smtp.sendmail(from_address, [recipient], msg.as_string())
admin_1      |   File "/usr/local/lib/python3.6/smtplib.py", line 881, in sendmail
admin_1      |     raise SMTPRecipientsRefused(senderrs)
admin_1      | smtplib.SMTPRecipientsRefused: {'root@home.lan': (554, b'5.7.1 <admin@home.lan>: Sender address rejected: Access denied')}
```

**Comment by edisoncosta** [comment]
Problem returned, can not send announcement.

Sender address rejected: not logged in

**Comment by kaiyou** [comment]
Sorry about the missed comment, which version is currently failing? I could not reproduce this either on master or on 1.5.

**Comment by mefistofeel** [comment]
I have similar problem.
Please see the logs:
`postfix/smtpd[126]: NOQUEUE: reject: RCPT from mailu_admin_1.mailu_default[172.19.0.8]: 553 5.7.1 <x@x.com>: Sender address rejected: not logged in; from=<x@x.com> to=<x@x.com> proto=ESMTP helo=<[172.19.0.8]>`

`[2018-03-06 12:54:10,064] ERROR in app: Exception on /ui/announcement [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/app/mailu/ui/access.py", line 36, in wrapper
    return callback(function, args, kwargs, (), {})
  File "/app/mailu/ui/access.py", line 19, in callback
    return function(*args, **kwargs)
  File "/app/mailu/ui/views/base.py", line 55, in announcement
    form.announcement_body.data)
  File "/app/mailu/models.py", line 170, in sendmail
    smtp.sendmail(from_address, [self.email], msg.as_string())
  File "/usr/local/lib/python3.6/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'x@x.com': (553, b'5.7.1 <x@x.com>: Sender address rejected: not logged in')}`

**Comment by kaiyou** [comment]
I finally pinpointed the source of this bug. It should be fixed soon.
