### ISSUE TITLE
[Bug] client_ip variable not defined -> results in 500 server error

### ISSUE THREAD

**Issue by Sacerdoss** [Mailu/Mailu#3314]
## Environment & Version

- `v2.27.1`
- Version: `2024.06.3`

## Description

The new _proxy method in `/core/admin/mailu/sso/base.py` logs a variable `client_ip` which is not defined in this method.

## Replication Steps

Login to the webmailer using proxy authentication

## Observed behaviour

A redirect to `/sso/login` results in a 500 error response

## Expected behaviour

login is successfull

## Logs
```
[2024-06-25 11:45:19,386] ERROR in app: Exception on /sso/login [GET]
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mailu/sso/views/base.py", line 17, in login
    return _proxy()
           ^^^^^^^^
  File "/app/mailu/sso/views/base.py", line 148, in _proxy
    flask.current_app.logger.info(f'Login succeeded by proxy created user: {user} from {client_ip} through {flask.request.remote_addr}.')
                                                                                        ^^^^^^^^^
UnboundLocalError: cannot access local variable 'client_ip' where it is not associated with a value
```

**Comment by Sacerdoss** [comment]
GH-3315 should fix this issue
