### ISSUE TITLE
LMTP delivery failing with 'KeyError' in admin logs after upgrading to 2024.06

### ISSUE THREAD

**Issue by WebSpider** [Mailu/Mailu#3403]
## Environment & Version

- `docker compose version v2.29.2`
- Version: `2024.06`
- OS: Ubuntu 22.04.4 LTS

## Description

Local delivery fails with an LMTP error

## Replication Steps

I updated to 2024.06 using the upgrade porcedure from 2.0.
Edit: maybe relevant: `INBOUND_TLS_ENFORCE` is set to `True`

Original container versions:
```
ghcr.io/mailu/nginx       2.0            8e086f3810ff   3 months ago    261MB
ghcr.io/mailu/admin       2.0            fb0e93452062   3 months ago    240MB
ghcr.io/mailu/clamav      2.0            32d93905efbc   3 months ago    287MB
ghcr.io/mailu/oletools    2.0            a7e500342676   3 months ago    237MB
ghcr.io/mailu/webmail     2.0            9ac41e28fc71   3 months ago    515MB
ghcr.io/mailu/radicale    2.0            799bbf72b56a   3 months ago    228MB
ghcr.io/mailu/rspamd      2.0            f5143134e95d   3 months ago    289MB
ghcr.io/mailu/unbound     2.0            1023aae15539   3 months ago    238MB
ghcr.io/mailu/dovecot     2.0            f5a96ccb2a1f   3 months ago    307MB
ghcr.io/mailu/postfix     2.0            6a91d0bef0d1   3 months ago    239MB
ghcr.io/mailu/fetchmail   2.0            b9ebf94fb197   3 months ago    234MB
```

## Observed behaviour

Incoming email works, but when postfix tries to deliver to mailbox, the following sequence of events occurs:

1. Front does a passdb lookup
2. Admin logs an error on the /internal/auth/email endpoint
3. Smtp delays delivery due to a temporary lookup error (the passdb lookup that fails)
## Expected behaviour

Delivery works.

## Logs

```
front-1            | Sep 05 09:20:45 lmtp(44912): Info: Connect from 192.168.203.5
front-1            | Sep 05 09:20:45 lmtp(44912): Debug: auth-master: passdb lookup(user@domain.nl): Started passdb lookup
front-1            | Sep 05 09:20:45 lmtp(44912): Debug: auth-master: conn unix:/run/dovecot/auth-userdb: Connecting
front-1            | Sep 05 09:20:45 lmtp(44912): Debug: auth-master: conn unix:/run/dovecot/auth-userdb (pid=12,uid=0): Client connected (fd=16)
front-1            | Sep 05 09:20:45 auth-worker(44910): Error: conn unix:auth-worker (pid=44891,uid=90): auth-worker<2>: lua(user@domain.nl,192.168.203.5): db-lua: 
front-1            | Sep 05 09:20:45 lmtp(44912): Error: auth-master: passdb lookup(user@domain.nl): Auth PASS lookup failed
front-1            | Sep 05 09:20:45 lmtp(44912): Debug: auth-master: passdb lookup(user@domain.nl): auth PASS input: 
front-1            | Sep 05 09:20:45 lmtp(44912): Debug: auth-master: passdb lookup(user@domain.nl): Passdb lookup failed
front-1            | Sep 05 09:20:45 lmtp(44912): Info: Disconnect from 192.168.203.5: Logged out (state=READY)
smtp-1             | Sep 05 09:20:45 mbox02 postfix/qmgr[369]: 4CBD81000C1: from=<SRS0=PQwK=QD=gmail.com=testaddress@mbox02.xcons.nl>, size=4464, nrcpt=1 (queue active)
smtp-1             | INFO:root:Connect 
smtp-1             | Sep 05 09:20:45 mbox02 postfix/lmtp[36688]: 56CBB100039: to=<user@domain.nl>, relay=front[192.168.203.2]:2525, delay=162585, delays=162585/0.06/0.09/0.02, dsn=4.3.0, status=deferred (host front[192.168.203.2] said: 451 4.3.0 <user@domain.nl> Temporary user lookup failure (in reply to RCPT TO command))
admin-1            | [2024-09-05 09:20:45,420] ERROR in app: Exception on /internal/auth/email [GET]
admin-1            | Traceback (most recent call last):
admin-1            |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
admin-1            |     response = self.full_dispatch_request()
admin-1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
admin-1            |     rv = self.handle_user_exception(e)
admin-1            |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/flask_restx/api.py", line 672, in error_router
admin-1            |     return original_handler(e)
admin-1            |            ^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
admin-1            |     rv = self.dispatch_request()
admin-1            |          ^^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
admin-1            |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
admin-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/mailu/internal/views/auth.py", line 32, in nginx_authentication
admin-1            |     headers = nginx.handle_authentication(flask.request.headers)
admin-1            |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/mailu/internal/nginx.py", line 79, in handle_authentication
admin-1            |     status, code = get_status(protocol, "encryption")
admin-1            |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/mailu/internal/nginx.py", line 137, in get_status
admin-1            |     return status, codes[protocol]
admin-1            |                    ~~~~~^^^^^^^^^^
admin-1            | KeyError: 'lmtp'
```

**Comment by WebSpider** [comment]
After turning off `INBOUND_TLS_ENFORCE` the mail delivery resumed.
So workaround known, but ... why doesn't LMTP work with this setting enabled, since it is used internally only?

**Comment by nextgens** [comment]
I propose we drop support for ``INBOUND_TLS_ENFORCE`` altogether; It never makes sense:
a) there is no standard for it
b) you can't enforce that the client securely connects ever: forcing TLS won't magically make the client connect securely. The "default" nowadays is opportunistic encryption without authentication ie: will defeat a passive attacker but not an active one. ``INBOUND_TLS_ENFORCE`` does not improve upon that.

**Comment by nextgens** [comment]
Once the images are built, please try reproducing it with:

```
export MAILU_VERSION=pr-3407
docker compose pull
docker compose up -d
```

**Comment by WebSpider** [comment]
Thanks, I'll try soon!

Removing support for `INBOUND_TLS_SUPPORT` seems like a big step tho, unless it's documented how to make the individual externally exposed services enforce transport security.

**Comment by nextgens** [comment]
That's the thing: the standard says that you shouldn't do it...

And you can't actually enforce that it's done properly. At best the knob catches accidental misconfiguration.

**Comment by WebSpider** [comment]
Interesting. Never realised that.

I have been using `INBOUND_TLS_SUPPORT` to make sure that inbound SMTP traffic was setup securely. 
I can fully understand it's hard to enforce MUA behaviour (submission/imap/etc) to be secure, given that it may break client compatibilty.

**Comment by nextgens** [comment]
``INBOUND_TLS_ENFORCE`` is not doing what you think it does. It has nothing to do with MUAs; Mailu will not let MUAs connect without transport security in its default configuration.

I'll just get rid of it.

**Comment by nextgens** [comment]
Hmm, the original PR and documentation do spell out why this is counterproductive: you will end up loosing emails.
https://github.com/Mailu/Mailu/pull/1610/files
