### ISSUE TITLE
Internal Server Error going to domain overview

### ISSUE THREAD

**Issue by xamanu** [Mailu/Mailu#499]
**Replicate**

After, I recently updated from version `1.4` to `master`:
Log into the admin interface (defaults to /admin/ location)
Manage Domains(/admin/ui/domain)

Get the below logging in the admin container, which I suspect is the cause:

```
admin_1      | [2018-06-17 13:11:03,904] ERROR in app: Exception on /ui/domain [GET]
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 36, in wrapper
admin_1      |     return callback(function, args, kwargs, (), {})
admin_1      |   File "/app/mailu/ui/access.py", line 19, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/views/domains.py", line 13, in domain_list
admin_1      |     return flask.render_template('domain/list.html')
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
admin_1      |     context, ctx.app)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
admin_1      |     rv = template.render(context)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
admin_1      |     return original_render(self, *args, **kwargs)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
admin_1      |     return self.environment.handle_exception(exc_info, True)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
admin_1      |     raise value.with_traceback(tb)
admin_1      |   File "/app/mailu/ui/templates/domain/list.html", line 1, in top-level template code
admin_1      |     {% extends "base.html" %}
admin_1      |   File "/app/mailu/ui/templates/base.html", line 3, in top-level template code
admin_1      |     {% extends "bootstrap/base.html" %}
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
admin_1      |     {% block doc -%}
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
admin_1      |     {%- block html %}
front_1      | 22.33.44.55 - - [17/Jun/2018:13:11:03 +0000] "GET /admin/ui/domain HTTP/1.1" 500 291 "https://mail.MYDOMAIN.COM/admin/ui/user/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
admin_1      |     {% block body -%}
admin_1      |   File "/app/mailu/ui/templates/base.html", line 56, in block "body"
admin_1      |     {% block content %}{% endblock %}
admin_1      |   File "/app/mailu/ui/templates/domain/list.html", line 14, in block "content"
admin_1      |     {% call macros.table() %}
admin_1      |   File "/usr/local/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
admin_1      |     rv = self._func(*arguments)
admin_1      |   File "/app/mailu/ui/templates/macros.html", line 92, in template
admin_1      |     {{ caller() }}
admin_1      |   File "/usr/local/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
admin_1      |     rv = self._func(*arguments)
admin_1      |   File "/app/mailu/ui/templates/domain/list.html", line 44, in template
admin_1      |     <td>{{ domain.aliases | count }} / {{ domain.max_aliases or '∞' }}</td>
admin_1      |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
admin_1      |     return getattr(obj, attribute)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
admin_1      |     return self.impl.get(instance_state(instance), dict_)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 599, in get
admin_1      |     value = self.callable_(state, passive)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 623, in _load_for_state
admin_1      |     return self._emit_lazyload(session, state, ident_key, passive)
admin_1      |   File "<string>", line 1, in <lambda>
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 747, in _emit_lazyload
admin_1      |     result = q(session).params(**params).all()
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 434, in all
admin_1      |     return list(self)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 98, in instances
admin_1      |     util.raise_from_cause(err)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
admin_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 79, in instances
admin_1      |     rows = [proc(row) for row in fetch]
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 79, in <listcomp>
admin_1      |     rows = [proc(row) for row in fetch]
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 436, in _instance
admin_1      |     tuple([row[column] for column in pk_cols]),
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 436, in <listcomp>
admin_1      |     tuple([row[column] for column in pk_cols]),
admin_1      |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 1208, in process
admin_1      |     return process_value(value, dialect)
admin_1      |   File "/app/mailu/models.py", line 45, in process_result_value
admin_1      |     localpart, domain_name = value.split('@')
admin_1      | 22.33.44.55 - - [17/Jun/2018:13:11:03 +0000] "GET /ui/domain HTTP/1.0" 500 291 "https://mail.MYDOMAIN.COM/admin/ui/user/settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
admin_1      | ValueError: too many values to unpack (expected 2)
```

Please help me to debug/repair. Thank you!

**Comment by kaiyou** [comment]
There is probably a failing migration script or your data was weird to begin with. Could you check in your user, alias and manager tables if there is any email field that does not contain a proper email address?

**Comment by xamanu** [comment]
Thanks for your ideas!

All emails are well formatted. I have one alias which is a catchall wildcard `%@MYDOMAIN.TLD`.
I saw in the `admin` containers' log also this error message, which might help:
`sqlalchemy.exc.StatementError: (builtins.ValueError) not enough values to unpack (expected 2, got 1) [SQL: 'SELECT user.created_at AS user_created_at, user.updated_at AS user_updated_at, user.comment AS user_comment, user.localpart AS user_localpart, user.password AS user_password, user.quota_bytes AS user_quota_bytes, user.global_admin AS user_global_admin, user.enabled AS user_enabled, user.enable_imap AS user_enable_imap, user.enable_pop AS user_enable_pop, user.forward_enabled AS user_forward_enabled, user.forward_destination AS user_forward_destination, user.forward_keep AS user_forward_keep, user.reply_enabled AS user_reply_enabled, user.reply_subject AS user_reply_subject, user.reply_body AS user_reply_body, user.reply_enddate AS user_reply_enddate, user.displayed_name AS user_displayed_name, user.spam_enabled AS user_spam_enabled, user.spam_threshold AS user_spam_threshold, user.domain_name AS user_domain_name, user.email AS user_email \nFROM user \nWHERE user.email = ?'] [parameters: [{'%(139645401536440 param)s': 'may'}]]`

Thanks!

**Comment by xamanu** [comment]
The problem occurs only on the following paths:
* `admin/ui/domain`
* `admin/ui/alias/edit/USER%MYDOMAIN.TLD`

I can still reach pages on:

* `admin/ui/user/*` (also edit)
* `admin/ui/manager/*` (add and delete)

**Comment by kaiyou** [comment]
Do you have a privacy issue dumping your alias table, which is the probable culprit here? Using ``sqlite3``, open the ``main.db`` and run ``.dump alias``. You may send it privately to ``contact@mailu.io`` if you wish.

**Comment by kaiyou** [comment]
Thank you for the dump (sent in private). The issue is related to some old aliases that are misformatted and the error was not detected because they were probably created before we added checks on local parts.

The culprits are some aliases in your database of the form ``local@domain.tld@domaon.tld``, you probably mistakenly entered the whole address in the local part field.

You should fix these using sqlite3 and things will be back to normal. I will also write a fix to avoid such formatting issues breaking Mailu entirely.

**Comment by xamanu** [comment]
I can confirm, this was the error and solution. Thanks a lot @kaiyou!

**Comment by gizocz** [comment]
I found the problem - there was an user (not alias) with two '@' in email. Still I thing, the admin should not show the "Internal Server Error" in this case.
