### ISSUE TITLE
Announcement failed to send

### ISSUE THREAD

**Issue by benyanke** [Mailu/Mailu#517]
When trying to send an announcement , I get the following error:

```
admin_1      | [2018-07-09 02:11:07,547] ERROR in app: Exception on /ui/announcement [POST]
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 36, in wrapper
admin_1      |     return callback(function, args, kwargs, (), {})
admin_1      |   File "/app/mailu/ui/access.py", line 19, in callback
smtp_1       | postfix/smtpd[112]: disconnect from mailu_admin_1.mailu_default[172.19.0.2] ehlo=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=4/5
front_1      | 24.159.246.197 - - [09/Jul/2018:02:11:07 +0000] "POST /admin/ui/announcement HTTP/1.1" 500 291 "https://yanke.io/admin/ui/announcement" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/67.0.3396.62 Chrome/67.0.3396.62 Safari/537.36"
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/views/base.py", line 55, in announcement
admin_1      |     form.announcement_body.data)
admin_1      |   File "/app/mailu/models.py", line 169, in sendmail
admin_1      |     smtp.sendmail(from_address, [self.email], msg.as_string())
admin_1      |   File "/usr/local/lib/python3.6/smtplib.py", line 881, in sendmail
admin_1      |     raise SMTPRecipientsRefused(senderrs)
admin_1      | smtplib.SMTPRecipientsRefused: {'admin@yanke.io': (553, b'5.7.1 <admin@yanke.io>: Sender address rejected: not logged in')}
admin_1      | 24.159.246.197 - - [09/Jul/2018:02:11:07 +0000] "POST /ui/announcement HTTP/1.0" 500 291 "https://yanke.io/admin/ui/announcement" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/67.0.3396.62 Chrome/67.0.3396.62 Safari/537.36"

```

The message seems counterintuitive, since I'm logged in. Thoughts?

**Comment by hoellen** [comment]
I think this is already fixed in master (see issue #309). But it's not in the current release.

**Comment by kaiyou** [comment]
Indeed, I'll see if the fix can be backported in 1.5, but I fear it is quite difficult.

**Comment by benyanke** [comment]
What's the release schedule like? I'm less worried about it if a new release is coming soon.

**Comment by kaiyou** [comment]
I will backport this today, sorry for the delays

**Comment by muhlemmer** [comment]
Isn't this the same as #643? Maybe we can close this one, as the other issue is more actively discussed.

**Comment by kaiyou** [comment]
It is, closing
