### ISSUE TITLE
Master branch: front container: "The 'requests-toolbelt>=0.3.0' distribution was not found and is required by acme"

### ISSUE THREAD

**Issue by bplein** [Mailu/Mailu#522]
I am running master branch (updated today).

If you run docker logs on the mailu_front_1 container, you see the following:

`Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests-toolbelt>=0.3.0' distribution was not found and is required by acme`

If you try running mailu master branch from a clean system (no prior configuration), this failure in LetsEncrypt means the system never comes up. 

If you install your system from 1.5, LetsEncrypt works fine, so you can get up and running, and then upgrade to Master branch, but then Letsencrypt is broken.

Given that it's important to pick up the 1.3.6 Roundcube updates with Master branch, we are stuck between running old Roundcube code (on mailu 1.5) or losing HTTPS support via Letsencrypt. 

Please advise!

**Comment by kaiyou** [comment]
Uh, sorry for the huge delay on this. I will investigate what the dependency became and how we should update the front container.

**Comment by kaiyou** [comment]
This should be fixed.
