### ISSUE TITLE
Unable to launch webdav container after update

### ISSUE THREAD

**Issue by LaurentMox** [Mailu/Mailu#611]
Hello,

I wanted to update my images so pulled new ones (i use "master".)
Now i cannot launch Radicale container anymore:

```
[36mwebdav_1     |[0m Traceback (most recent call last):
[36mwebdav_1     |[0m   File "/usr/bin/radicale", line 6, in <module>
[36mwebdav_1     |[0m     from pkg_resources import load_entry_point
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
[36mwebdav_1     |[0m     @_call_aside
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
[36mwebdav_1     |[0m     f(*args, **kwargs)
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
[36mwebdav_1     |[0m     working_set = WorkingSet._build_master()
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
[36mwebdav_1     |[0m     return cls._build_from_requirements(__requires__)
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
[36mwebdav_1     |[0m     dists = ws.resolve(reqs, Environment())
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
[36mwebdav_1     |[0m     raise DistributionNotFound(req, requirers)
[36mwebdav_1     |[0m pkg_resources.DistributionNotFound: The 'vobject==0.9.5' distribution was not found and is required by Radicale
[36mwebdav_1     |[0m Traceback (most recent call last):
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
[36mwebdav_1     |[0m     ws.require(__requires__)
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
[36mwebdav_1     |[0m     needed = self.resolve(parse_requirements(requirements))
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
[36mwebdav_1     |[0m     raise VersionConflict(dist, req).with_context(dependent_req)
[36mwebdav_1     |[0m pkg_resources.ContextualVersionConflict: (vobject 0.9.6 (/usr/lib/python3.6/site-packages), Requirement.parse('vobject==0.9.5'), {'Radicale'})
[36mwebdav_1     |[0m 
[36mwebdav_1     |[0m During handling of the above exception, another exception occurred:
[36mwebdav_1     |[0m 
[36mwebdav_1     |[0m Traceback (most recent call last):
[36mwebdav_1     |[0m   File "/usr/bin/radicale", line 6, in <module>
[36mwebdav_1     |[0m     from pkg_resources import load_entry_point
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
[36mwebdav_1     |[0m     @_call_aside
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
[36mwebdav_1     |[0m     f(*args, **kwargs)
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
[36mwebdav_1     |[0m     working_set = WorkingSet._build_master()
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
[36mwebdav_1     |[0m     return cls._build_from_requirements(__requires__)
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
[36mwebdav_1     |[0m     dists = ws.resolve(reqs, Environment())
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
[36mwebdav_1     |[0m     raise DistributionNotFound(req, requirers)
[36mwebdav_1     |[0m pkg_resources.DistributionNotFound: The 'vobject==0.9.5' distribution was not found and is required by Radicale
[36mwebdav_1     |[0m Traceback (most recent call last):
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
[36mwebdav_1     |[0m     ws.require(__requires__)
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
[36mwebdav_1     |[0m     needed = self.resolve(parse_requirements(requirements))
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
[36mwebdav_1     |[0m     raise VersionConflict(dist, req).with_context(dependent_req)
[36mwebdav_1     |[0m pkg_resources.ContextualVersionConflict: (vobject 0.9.6 (/usr/lib/python3.6/site-packages), Requirement.parse('vobject==0.9.5'), {'Radicale'})
[36mwebdav_1     |[0m 
[36mwebdav_1     |[0m During handling of the above exception, another exception occurred:
[36mwebdav_1     |[0m 
[36mwebdav_1     |[0m Traceback (most recent call last):
[36mwebdav_1     |[0m   File "/usr/bin/radicale", line 6, in <module>
[36mwebdav_1     |[0m     from pkg_resources import load_entry_point
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
[36mwebdav_1     |[0m     @_call_aside
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
[36mwebdav_1     |[0m     f(*args, **kwargs)
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
[36mwebdav_1     |[0m     working_set = WorkingSet._build_master()
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
[36mwebdav_1     |[0m     return cls._build_from_requirements(__requires__)
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
[36mwebdav_1     |[0m     dists = ws.resolve(reqs, Environment())
[36mwebdav_1     |[0m   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
[36mwebdav_1     |[0m     raise DistributionNotFound(req, requirers)
[36mwebdav_1     |[0m pkg_resources.DistributionNotFound: The 'vobject==0.9.5' distribution was not found and is required by Radicale
```

It seems to have a conflict between 2 versions of vobject (0.9.5 & 0.9.6).
Any idea of how to fix this please?

Thanks a lot!

**Comment by aminb** [comment]
I noticed this too. It was indeed due to the vobject dep in the radicale package on alpine testing, which is now updated and fixed. Pulling the newest mailu/webdav should do it.

**Comment by LaurentMox** [comment]
I confirm it's now fixed !
Thank you !

**Comment by aminb** [comment]
Cheers!
