### ISSUE TITLE
Sqlalchemy errors in logs

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#671]
On my testing server, I'm seeing frequent logs with failed sql queries, admin. This is happening in the Master branch or any other branch I've been testing today. I was doing primarily logins trough webmail. Not sure if that matters. There does not seem to be any broken or missing functionality.

Because we did many changes to the DB interface lately, I think this has slipped through review somehow. I don't have time to debug at the moment, so I'm just raising the issue.

```
admin_1      | [2018-10-19 14:45:24,928] ERROR in app: Exception on /internal/auth/email [GET]
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
admin_1      |     context = constructor(dialect, self, conn, *args)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in _init_compiled
admin_1      |     param.append(processors[key](compiled_params[key]))
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1160, in process
admin_1      |     return process_param(value, dialect)
admin_1      |   File "/app/mailu/models.py", line 38, in process_bind_param
admin_1      |     localpart, domain_name = value.split('@')
admin_1      | ValueError: not enough values to unpack (expected 2, got 1)
admin_1      | 
admin_1      | The above exception was the direct cause of the following exception:
admin_1      | 
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 544, in __inner
admin_1      |     return obj(*a, **k)
admin_1      |   File "/app/mailu/internal/views/auth.py", line 17, in nginx_authentication
admin_1      |     headers = nginx.handle_authentication(flask.request.headers)
admin_1      |   File "/app/mailu/internal/nginx.py", line 40, in handle_authentication
admin_1      |     user = models.User.query.get(user_email)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 882, in get
admin_1      |     ident, loading.load_on_ident)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 916, in _get_impl
admin_1      |     return fallback_fn(self, key)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 232, in load_on_ident
admin_1      |     return q.one()
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2848, in one
admin_1      |     ret = self.one_or_none()
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2818, in one_or_none
admin_1      |     ret = list(self)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
admin_1      |     return self._execute_and_instances(context)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2912, in _execute_and_instances
admin_1      |     result = conn.execute(querycontext.statement, self._params)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
admin_1      |     return meth(self, multiparams, params)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
admin_1      |     return connection._execute_clauseelement(self, multiparams, params)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
admin_1      |     compiled_sql, distilled_params
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1132, in _execute_context
admin_1      |     None, None)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
admin_1      |     exc_info
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
admin_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
admin_1      |     raise value.with_traceback(tb)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
admin_1      |     context = constructor(dialect, self, conn, *args)
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 667, in _init_compiled
admin_1      |     param.append(processors[key](compiled_params[key]))
admin_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 1160, in process
admin_1      |     return process_param(value, dialect)
admin_1      |   File "/app/mailu/models.py", line 38, in process_bind_param
admin_1      |     localpart, domain_name = value.split('@')
admin_1      | sqlalchemy.exc.StatementError: (builtins.ValueError) not enough values to unpack (expected 2, got 1) [SQL: 'SELECT user.created_at AS user_created_at, user.updated_at AS user_updated_at, user.comment AS user_comment, user.localpart AS user_localpart, user.password AS user_password, user.quota_bytes AS user_quota_bytes, user.quota_bytes_used AS user_quota_bytes_used, user.global_admin AS user_global_admin, user.enabled AS user_enabled, user.enable_imap AS user_enable_imap, user.enable_pop AS user_enable_pop, user.forward_enabled AS user_forward_enabled, user.forward_destination AS user_forward_destination, user.forward_keep AS user_forward_keep, user.reply_enabled AS user_reply_enabled, user.reply_subject AS user_reply_subject, user.reply_body AS user_reply_body, user.reply_enddate AS user_reply_enddate, user.displayed_name AS user_displayed_name, user.spam_enabled AS user_spam_enabled, user.spam_threshold AS user_spam_threshold, user.domain_name AS user_domain_name, user.email AS user_email \nFROM user \nWHERE user.email = ?'] [parameters: [{'%(140279936631640 param)s': 'lin'}]]
```

**Comment by hoellen** [comment]
I think this is a duplicate of #585

**Comment by muhlemmer** [comment]
You're right. Closing
