### ISSUE TITLE
"exec: \"python\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by jtullett** [Mailu/Mailu#714]
Hi guys

Trying to start up a mailu container, and it returns an error (full log below):

```
root@www2:/opt/containers/mailu# docker-compose run --rm admin python manage.py admin root mydomain.com password
Starting mailu_redis_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: domain
```

I saw a couple of very old similar issues, but they're probably unrelated. Any suggestions?

Full traceback:
```
root@www2:/opt/containers/mailu# docker-compose run --rm admin python manage.py admin root mydomain.com password
Starting mailu_redis_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: domain

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 298, in <module>
    manager.run()
  File "/usr/local/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 30, in admin
    domain = models.Domain.query.get(domain_name)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 864, in get
    return self._get_impl(ident, loading.load_on_ident)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 897, in _get_impl
    return fallback_fn(self, key)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
    return q.one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_       instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on       _connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_causeelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: domain [SQL: 'SELECT domain.created_at AS domain_created_at, domain.updated_at AS domain_updated_at, domain.comment AS domain       _comment, domain.name AS domain_name, domain.max_users AS domain_max_users, domain.max_aliases AS do       main_max_aliases, domain.max_quota_bytes AS domain_max_quota_bytes \nFROM domain \nWHERE domain.name        = ?'] [parameters: ('mydomain.com',)]
```

**Comment by jtullett** [comment]
Update: the error above was starting v1.5. When starting with version=master, I get a different error:


`ERROR: Cannot start service admin: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown`

**Comment by muhlemmer** [comment]
These problems not related... 

So **first**, it seems that in your first comment https://github.com/Mailu/Mailu/issues/714#issue-385202660 the tables in the database where not created (yet). The tables get created by the admin container on the fist run. Did you do `docker-compose up -d` before attempting to create the fist user? Did you follow **all** steps in the documentation? I assume this is a fresh install. Can you delete you `/mailu` directories? Then run:
```
docker-compose up -d
docker-compose logs admin
```
Somewhere in the top of the logs you should see:
```
admin_1      | INFO  [alembic.runtime.migration] Running upgrade  -> ff0417f4318f, Initial schema
admin_1      | INFO  [alembic.runtime.migration] Running upgrade ff0417f4318f -> c5696b48442d, Add wildcard aliases
admin_1      | /usr/local/lib/python3.7/site-packages/alembic/util/messaging.py:69: UserWarning: Skipping unsupported ALTER for creation of implicit constraint
admin_1      |   warnings.warn(msg)
admin_1      | INFO  [alembic.runtime.migration] Running upgrade c5696b48442d -> a4accda8a8c7, Update the spam threshold default value
admin_1      | INFO  [alembic.runtime.migration] Running upgrade a4accda8a8c7 -> dc8c25cf5b98, Add metadata related to fetches
admin_1      | INFO  [alembic.runtime.migration] Running upgrade dc8c25cf5b98 -> 27ae2f102682, spam_threshold in percent
admin_1      | /usr/local/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py:603: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
admin_1      |   'storage.' % (dialect.name, dialect.driver))
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 27ae2f102682 -> 12e9a4f6ed73, Set the spam threshold as an integer
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 12e9a4f6ed73 -> 2335c80a6bc3, Add a maximum quota per domain
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 2335c80a6bc3 -> 3f6994568962, Add keep as an option in fetches
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 3f6994568962 -> 73e56bad5ec5, Add the ability to keep forwarded messages
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 73e56bad5ec5 -> c9a0b4e653cf, Add alternative domains
admin_1      | INFO  [alembic.runtime.migration] Running upgrade c9a0b4e653cf -> c162ac88012a, Add relayed domains
admin_1      | INFO  [alembic.runtime.migration] Running upgrade c162ac88012a -> 9c28df23f77e, Set the nocase collation on the user and alias tables
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 9c28df23f77e -> 9400a032eb1a, Add authentication tokens
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 9400a032eb1a -> 77aa22ad72e2, Add an enddate for the vacation mode
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 77aa22ad72e2 -> 423155f8fc15, Enable signup per domain
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 423155f8fc15 -> 49d77a93118e, Add enabled flag to user model
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 49d77a93118e -> 049fed905da7, Enforce the nocase collation on the email table
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 049fed905da7 -> 25fd6c7bcb4a, Add a column for used quota
admin_1      | INFO  [alembic.runtime.migration] Running upgrade 25fd6c7bcb4a -> 3b281286c7bd, Add a start day for vacations
admin_1      | [2018-12-02 22:14:30 +0000] [17] [INFO] Starting gunicorn 19.7.1
```
Please report back if there are any errors in this stage. If everything went well, you can now create the first user.

Regarding your **second error**. We've moved to python3 on **master**. It seems I forgot to update the docs in this regards. After you've done the instructions above, this should work:
```
docker-compose run --rm admin python3 manage.py admin root mydomain.com password
```

I will not update the docs for this anymore, because we have a PR pending in which the syntax will change altogether and includes the doc update for this. (#670).

**Comment by jtullett** [comment]
Thanks for the detailed response! I haven't had time to check, but I think it might also have been resource-related; the VM in question was running low on memory thanks to other components churning a bit so I'll resolve that first to eliminate it as factor. Hadn't realised Mailu would start as many separate containers as it does, but the Docker-specific overhead shouldn't be much of an issue, just that the host itself was struggling. I'll try your other points, esp re python3, this weekend. Thanks again!

**Comment by muhlemmer** [comment]
Docs server is up, closing this issue
