### ISSUE TITLE
When WELCOME=true, creating a user fails

### ISSUE THREAD

**Issue by Nebukadneza** [Mailu/Mailu#832]
With welcome email functionality enabled, creating a user results in 500 Internal Server Error …

```
smtp_1       | postfix/smtpd[134]: connect from mailu_admin_1.mailu_default[192.168.203.7]
smtp_1       | INFO:root:Connect 
smtp_1       | DEBUG:root:Received bytearray(b'transport *')
smtp_1       | DEBUG:root:Request transport/*
smtp_1       | DEBUG:root:Table get *
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/transport/* HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'transport *')
smtp_1       | DEBUG:root:Request transport/*
smtp_1       | DEBUG:root:Table get *
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/transport/* HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'domain test02.usrpro.io')
smtp_1       | DEBUG:root:Request domain/test02.usrpro.io
smtp_1       | DEBUG:root:Table get test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/domain/test02.usrpro.io HTTP/1.1" 200 19 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Table get test02.usrpro.io is test02.usrpro.io
smtp_1       | DEBUG:root:Replying b'OK test02.usrpro.io'
smtp_1       | DEBUG:root:Received bytearray(b'transport test02.usrpro.io')
smtp_1       | DEBUG:root:Request transport/test02.usrpro.io
smtp_1       | DEBUG:root:Table get test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/transport/test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'transport admin@test02.usrpro.io')
smtp_1       | DEBUG:root:Request transport/admin@test02.usrpro.io
smtp_1       | DEBUG:root:Table get admin@test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/transport/admin@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'domain test02.usrpro.io')
smtp_1       | DEBUG:root:Request domain/test02.usrpro.io
smtp_1       | DEBUG:root:Table get test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/domain/test02.usrpro.io HTTP/1.1" 200 19 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Table get test02.usrpro.io is test02.usrpro.io
smtp_1       | DEBUG:root:Replying b'OK test02.usrpro.io'
smtp_1       | DEBUG:root:Received bytearray(b'transport test02.usrpro.io')
smtp_1       | DEBUG:root:Request transport/test02.usrpro.io
smtp_1       | DEBUG:root:Table get test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/transport/test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'transport lclv@test02.usrpro.io')
smtp_1       | DEBUG:root:Request transport/lclv@test02.usrpro.io
smtp_1       | DEBUG:root:Table get lclv@test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/transport/lclv@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'domain test02.usrpro.io')
smtp_1       | DEBUG:root:Request domain/test02.usrpro.io
smtp_1       | DEBUG:root:Table get test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:23 +0000] "GET /internal/postfix/domain/test02.usrpro.io HTTP/1.1" 200 19 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Table get test02.usrpro.io is test02.usrpro.io
smtp_1       | DEBUG:root:Replying b'OK test02.usrpro.io'
smtp_1       | DEBUG:root:Received bytearray(b'transport test02.usrpro.io')
smtp_1       | DEBUG:root:Request transport/test02.usrpro.io
smtp_1       | DEBUG:root:Table get test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:24 +0000] "GET /internal/postfix/transport/test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'transport admin@test02.usrpro.io')
smtp_1       | DEBUG:root:Request transport/admin@test02.usrpro.io
smtp_1       | DEBUG:root:Table get admin@test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:24 +0000] "GET /internal/postfix/transport/admin@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | INFO:root:Connect 
smtp_1       | DEBUG:root:Received bytearray(b'alias admin@test02.usrpro.io')
smtp_1       | DEBUG:root:Request alias/admin@test02.usrpro.io
smtp_1       | DEBUG:root:Table get admin@test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:24 +0000] "GET /internal/postfix/alias/admin@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'mailbox admin@test02.usrpro.io')
smtp_1       | DEBUG:root:Request mailbox/admin@test02.usrpro.io
smtp_1       | DEBUG:root:Table get admin@test02.usrpro.io
admin_1      | 192.168.203.10 - - [13/Jan/2019:09:34:24 +0000] "GET /internal/postfix/mailbox/admin@test02.usrpro.io HTTP/1.1" 404 233 "-" "Python/3.6 aiohttp/3.5.4"
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | postfix/smtpd[134]: NOQUEUE: reject: RCPT from mailu_admin_1.mailu_default[192.168.203.7]: 550 5.1.0 <admin@test02.usrpro.io>: Sender address rejected: User unknown in virtual mailbox table; from=<admin@test02.usrpro.io> to=<lclv@test02.usrpro.io> proto=ESMTP helo=<[192.168.203.7]>
smtp_1       | postfix/smtpd[134]: disconnect from mailu_admin_1.mailu_default[192.168.203.7] ehlo=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=4/5
admin_1      | [2019-01-13 09:34:24,136] ERROR in app: Exception on /ui/user/create/test02.usrpro.io [POST]
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 28, in wrapper
admin_1      |     return callback(function, args, kwargs, dargs, dkwargs)
admin_1      |   File "/app/mailu/ui/access.py", line 19, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/ui/views/users.py", line 39, in user_create
admin_1      |     user.send_welcome()
admin_1      |   File "/app/mailu/models.py", line 415, in send_welcome
admin_1      |     app.config["WELCOME_BODY"])
admin_1      |   File "/app/mailu/models.py", line 258, in sendmail
admin_1      |     smtp.sendmail(from_address, [to_address], msg.as_string())
admin_1      |   File "/usr/lib/python3.6/smtplib.py", line 881, in sendmail
admin_1      |     raise SMTPRecipientsRefused(senderrs)
admin_1      | smtplib.SMTPRecipientsRefused: {'lclv@test02.usrpro.io': (550, b'5.1.0 <admin@test02.usrpro.io>: Sender address rejected: User unknown in virtual mailbox table')}
admin_1      | 89.245.250.186 - - [13/Jan/2019:09:34:24 +0000] "POST /ui/user/create/test02.usrpro.io HTTP/1.0" 500 291 "https://test02.usrpro.io/admin/ui/user/create/test02.usrpro.io" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
```

**Comment by Nebukadneza** [comment]
This was, once more, a user error. In my test setup, the `POSTMASTER` account didn’t exist, and that’s the user which wasn’t found. I first thought it’d be the new user who didn’t exist yet (some kind of race, but that’d have been strange because the welcome mail came after `db.commit()`).
